[
    object,
    uuid(c4910d71-ba7d-11cd-94e8-08001701a8a3),
    pointer_default(unique)
]


interface ILookup : IUnknown
{
    import "unknwn.idl";

    HRESULT LookupByName(
    [in] LPTSTR lpName, 
    [out, string] WCHAR **lplpNumber);

    HRESULT LookupByNumber(
    [in] LPTSTR lpNumber, 
    [out, string] WCHAR ** lplpName);

}
