# KallistiOS ##version##
#
# arch/dreamcast/math/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/09/05 07:32:13 bardtx Exp $

# Dreamcast-specific math functions

OBJS = fmath.o matrix.o matrix3d.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


