# KallistiOS ##version##
#
# kernel/debug/Makefile
# Copyright (C)2004 Dan Potter
#   
# $Id: Makefile,v 1.3 2002/08/13 04:54:22 bardtx Exp $

OBJS = dbgio.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab

