#------------------------------------------------------------------------------
#k2nefert.mak
#------------------------------------------------------------------------------

PROJECT =	k2nefert

PROJECT_SRC	= \
		DISPSTR.C\
		KMNEFERT.C\
		MAIN.C\
		PVRLOGO.C\
		RIVETS.C\
		sbinit.c\
		TEXCHAR.C\
		TRANSFOR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
