# KallistiOS ##version##
#
# misc/Makefile
# (c)2000-2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2003/07/15 07:55:00 bardtx Exp $

BUILD_TARGET=loadable/libkos

OBJS = bspline.o img.o pcx_small.o netcfg.o
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab


