# KallistiOS ##version##
#
# examples/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.1.1.1 2001/09/26 07:05:13 bardtx Exp $

all:
	$(KOS_MAKE) -C $(KOS_ARCH)

clean:
	$(KOS_MAKE) -C $(KOS_ARCH) clean
		

