#------------------------------------------------------------------------------
#bup2a.mak
#------------------------------------------------------------------------------

PROJECT =	bup2a

PROJECT_SRC	= \
		backup.c\
		model.c\
		njloop.c\
		SAVEDATA.C\
		sbinit.c\
		t009.c\
		test.c\
		global32.src\

SYSTEM_LIBS	= \
		nindows\
			


OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
