# KallistiOS ##version##
#
# arch/gba Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.1.1.1 2001/09/26 07:05:11 bardtx Exp $
	
SUBDIRS=hardware kernel

include $(KOS_BASE)/Makefile.rules

all: subdirs
clean: clean_subdirs
