# KallistiOS ##version##
#
# examples/dreamcast/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.17 2003/05/23 02:05:41 bardtx Exp $

all:
	$(KOS_MAKE) -C 2ndmix
	$(KOS_MAKE) -C basic
	$(KOS_MAKE) -C libdream
	$(KOS_MAKE) -C kgl
	$(KOS_MAKE) -C hello
	$(KOS_MAKE) -C sound
	$(KOS_MAKE) -C png
	$(KOS_MAKE) -C network
	$(KOS_MAKE) -C vmu
	$(KOS_MAKE) -C conio
	$(KOS_MAKE) -C pvr
	$(KOS_MAKE) -C video
	$(KOS_MAKE) -C lua
	$(KOS_MAKE) -C parallax
	$(KOS_MAKE) -C modem
ifdef KOS_CCPLUS
	$(KOS_MAKE) -C cpp
	$(KOS_MAKE) -C tsunami
endif

clean:
	$(KOS_MAKE) -C 2ndmix clean
	$(KOS_MAKE) -C basic clean
	$(KOS_MAKE) -C libdream clean
	$(KOS_MAKE) -C kgl clean
	$(KOS_MAKE) -C hello clean
	$(KOS_MAKE) -C sound clean
	$(KOS_MAKE) -C png clean
	$(KOS_MAKE) -C network clean
	$(KOS_MAKE) -C vmu clean
	$(KOS_MAKE) -C conio clean
	$(KOS_MAKE) -C pvr clean
	$(KOS_MAKE) -C video clean
	$(KOS_MAKE) -C lua clean
	$(KOS_MAKE) -C parallax clean
	$(KOS_MAKE) -C modem clean
	$(KOS_MAKE) -C cpp clean
	$(KOS_MAKE) -C tsunami clean
		
dist:
	$(KOS_MAKE) -C 2ndmix dist
	$(KOS_MAKE) -C basic dist
	$(KOS_MAKE) -C libdream dist
	$(KOS_MAKE) -C kgl dist
	$(KOS_MAKE) -C hello dist
	$(KOS_MAKE) -C sound dist
	$(KOS_MAKE) -C png dist
	$(KOS_MAKE) -C network dist
	$(KOS_MAKE) -C vmu dist
	$(KOS_MAKE) -C conio dist
	$(KOS_MAKE) -C pvr dist
	$(KOS_MAKE) -C video dist
	$(KOS_MAKE) -C lua dist
	$(KOS_MAKE) -C parallax dist
	$(KOS_MAKE) -C modem dist
ifdef KOS_CCPLUS
	$(KOS_MAKE) -C cpp dist
	$(KOS_MAKE) -C tsunami dist
endif


