

typedef struct 
{
    int  iTag;
    char *szText;
} ERRSPEC;


#define NO_LINE -1

enum ErrorCodes
{
	errNone = CFileException::none,
	errGeneric = CFileException::generic,
	errFileNotFound = CFileException::fileNotFound,
	errBadPath = CFileException::badPath,
	errTooManyOpenFiles = CFileException::tooManyOpenFiles,
	errAccessDenied = CFileException::accessDenied,
	errInvalidFile = CFileException::invalidFile,
	errRemoveCurrentDir = CFileException::removeCurrentDir,
	errDirectoryFull = CFileException::directoryFull,
	errBadSeek = CFileException::badSeek,
	errHardIO = CFileException::hardIO,
	errSharingViolation = CFileException::sharingViolation,
	errLockViolation = CFileException::lockViolation,
	errDiskFull = CFileException::diskFull,
	errEndOfFile = CFileException::endOfFile,

    errBadFieldRef,
    errCantAppend,
    errCantDeduceOutput,
    errCmdSyntaxDefine,
    errCmdSyntaxExpectedFlagFollowup,
    errCmdSyntaxHelp,
    errCmdSyntaxTab,
    errCmdSyntaxUnknownFlag,
    errLogDuplicate,
    errLogMismatchedQuotes,
    errMemory,
    errMismatchedResponseQuotes,
    errMultilineOverflow,
    errNoFiles,
    errNoFormatFile,
    errTagTooBig,
    errTopicCtxTooLong,
    errTopicNameTooLong,
    exprerrDocTokenTooLong,
    exprerrExpectedExprArgument,
    exprerrExpectedExprOperator,
    exprerrExprMismatchedParens,
    fmterrBadEntryCount,
    fmterrBadFieldCount,
    fmterrBadFieldReference,
    fmterrBadFilenameExtension,
    fmterrBadFmtEntry,
    fmterrBadIfExpression,
    fmterrBadSection,
    fmterrBadSrcParse,
    fmterrBadSrcType,
    fmterrBadTagName,
    fmterrBadTokenCode,
    fmterrDuplicateEntry,
    fmterrExpectedCloseParen,
    fmterrExpectedComma,
    fmterrExpectedEol,
    fmterrExpectedEqual,
    fmterrExpectedExtension,
    fmterrExpectedFieldCount,
    fmterrExpectedFieldNum,
    fmterrExpectedName,
    fmterrExpectedOpenParen,
    fmterrExpectedPeriod,
	fmterrExpectedTokenName,
    fmterrFieldReferenceRange,
    fmterrFileOutputNum,
    fmterrInvalidTag,
    fmterrNameBadSpec,
    fmterrNameCount,
    fmterrNoFieldCount,
    fmterrNoTagName,
    fmterrNoTokenDefinitions,
    fmterrOrphanedTag,
    fmterrParaExpectedExFlag,
    fmterrParaExpectedLevel,
    fmterrTooManyIfs,
    fmterrTopicExpectedSortWeight,
    
    warnBadConstantReference,
    warnBadContextReference,
    warnBadDiagramReference,
    warnBadFieldReference,
    warnBadFmtEscapeSequence,
    warnBadIndexReference,
	fmterrBadMapFieldReference,
    warnBadTopicFieldReference,
	warnCantTransferAux,
    warnFileTypeUnknown,
    warnMissingTextTagTerminator,
    warnNoConstFormat,
    warnNoDiagramFormat,
    warnNoIndexFormat,
    warnNoParaFormat,
    warnNoPendingFields,
    warnNoTextFormat,
    warnNoTopicFormat,
	warnOrphanedAuxPara,
	warnSrcFieldsIncomplete,
	warnSrcFieldsMultiline,
    warnSrcFieldsUnavailable,
    warnTagExclSyntax,
    warnTagFieldUnavailable,
    warnTagFieldUnavailableForDiagram,
    warnTooManyFields,
    warnTooManyTextFields,
    warnTopicFieldUnavailable,
    warnUnknownBuildConstant,
    warnUnknownParaTag,
    warnUnknownTopicTag,
    warnWantTopicTag,
    warnWrongNumFields,
    warnWrongNumTextFields,
};

void PrintError(const char *szFilename, long lLine, int nError);
