#------------------------------------------------------------------------------
#gdda.mak
#------------------------------------------------------------------------------

PROJECT =	gdda

PROJECT_SRC	= \
		main.c\
		sbinit.c\
		sndutls.c\

SYSTEM_LIBS     = \
                sg_sd\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
