#------------------------------------------------------------------------------
#k2tree.mak
#------------------------------------------------------------------------------

PROJECT =	k2tree

PROJECT_SRC	= \
		BARK.C\
		DISPSTR.C\
		FOREST.C\
		KMTREE.C\
		KMTTOOL.C\
		LEAF.C\
		MAIN.C\
		sbinit.c\
		TEXCHAR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
