# KallistiOS ##version##
#
# modules/drivers/dreamcast Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.2 2003/07/15 07:55:01 bardtx Exp $

DIRS = maple net_bba net_la

include ../../../Makefile.subdirs

