#------------------------------------------------------------------------------
#k2blend.mak
#------------------------------------------------------------------------------

PROJECT =	k2blend

PROJECT_SRC	= \
		BACK.C\
		DISPSTR.C\
		GOLD.C\
		KMBLEND.C\
		MAIN.C\
		OPAQ.C\
		sbinit.c\
		TEXCHAR.C\
		TRANS.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
