[!if=(ConnectionPointsEnabled, "TRUE")]
[!crlf]
	[
		uuid([!InterfaceGUIDCP]),
		helpstring("_[!InterfaceName]Events Interface")
	]
	dispinterface _[!InterfaceName]Events
	{
		properties:
		methods:
	};
[!endif]
[!crlf]
	[
		uuid([!ObjectGUID]),
		helpstring("[!TypeName]")
	]
	coclass [!CoClassName]
	{
		interface IUnknown;
[!if=(ConnectionPointsEnabled, "TRUE")]
		[default, source] dispinterface _[!InterfaceName]Events;
[!endif]
	};
