# KallistiOS 1.1.6
#
# Root Makefile.prefab
# (c)2000 Dan Potter
#   
# $Id: Makefile.prefab,v 1.1.1.1 2001/09/26 07:04:59 bardtx Exp $


# Global KallistiOS Makefile include
# Define "SUBDIRS" and "OBJS", and then include this file;
#   it will handle a lot of your build process.

ifeq (b$(BUILD_TARGET),b)
	BUILD_TARGET = kernel
endif

all: $(OBJS) subdirs
	-cp $(OBJS) $(KOS_BASE)/$(BUILD_TARGET)/build/

clean: clean_subdirs
	-rm -f $(OBJS) *.bck

include $(KOS_BASE)/Makefile.rules


