# KallistiOS ##version##
#
# thread/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.5 2003/06/19 04:29:01 bardtx Exp $

OBJS =  sem.o cond.o mutex.o genwait.o # msg.o
OBJS += process.o thread.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



