# KallistiOS ##version##
#
# arch/dreamcast/hardware/modem/Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/06/19 04:20:59 bardtx Exp $

BUILD_TARGET := loadable/libkos

OBJS = mdata.o mintr.o modem.o msegbuf.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab

