# KallistiOS ##version##
#
# examples/dreamcast/basic/mmu/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/10/08 07:51:21 bardtx Exp $

all:
	$(KOS_MAKE) -C pvrmap
	$(KOS_MAKE) -C nullptr

clean:
	$(KOS_MAKE) -C pvrmap clean
	$(KOS_MAKE) -C nullptr clean
		
dist:
	$(KOS_MAKE) -C pvrmap dist
	$(KOS_MAKE) -C nullptr dist


