#------------------------------------------------------------------------------
#bupd1.mak
#------------------------------------------------------------------------------

PROJECT =	bupd1

PROJECT_SRC	= \
		backup.c\
		njloop.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
