#------------------------------------------------------------------------------
# Vase.mak
#------------------------------------------------------------------------------

PROJECT =	Vase

PROJECT_SRC	= \
		data.c\
		kmbump.c\
		kmlight.c\
		kmmatrix.c\
		kmmisc.c\
		kmprint3d.c\
		kmshell.c\
		kmtexture.c\
		kmtimer.c\
		kmtransform.c\
		sbinit.c\
		vase.c\
		vqcalc.c\

OPTIMIZE =	0

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
