# KallistiOS ##version##
#
# arch/ps2/sbios/Makefile
# (c)2002 Dan Potter
#
# $Id: Makefile,v 1.1 2002/10/27 23:39:23 bardtx Exp $

# Main SBIOS support routines
OBJS = sbios_init_shutdown.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab



