# KallistiOS 1.1.6
#
# examples/dreamcast/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.4 2002/01/11 06:10:46 bardtx Exp $

all:
	$(KOS_MAKE) -C 2ndmix
	$(KOS_MAKE) -C threads
	$(KOS_MAKE) -C libdream
	$(KOS_MAKE) -C kosh
	$(KOS_MAKE) -C gl
	$(KOS_MAKE) -C hello
	$(KOS_MAKE) -C ghettoplay-vorbis
	$(KOS_MAKE) -C png

clean:
	$(KOS_MAKE) -C 2ndmix clean
	$(KOS_MAKE) -C threads clean
	$(KOS_MAKE) -C libdream clean
	$(KOS_MAKE) -C kosh clean
	$(KOS_MAKE) -C gl clean
	$(KOS_MAKE) -C hello clean
	$(KOS_MAKE) -C ghettoplay-vorbis clean
	$(KOS_MAKE) -C png clean
		
dist:
	$(KOS_MAKE) -C 2ndmix dist
	$(KOS_MAKE) -C threads dist
	$(KOS_MAKE) -C libdream dist
	$(KOS_MAKE) -C kosh dist
	$(KOS_MAKE) -C gl dist
	$(KOS_MAKE) -C hello dist
	$(KOS_MAKE) -C ghettoplay-vorbis dist
	$(KOS_MAKE) -C png dist


