# KallistiOS ##version##
#
# arch/dreamcast/fs/Makefile
# Copyright (C)2003 Dan Potter
#
# $Id: Makefile,v 1.1 2003/06/19 04:20:59 bardtx Exp $

BUILD_TARGET=loadable/libkos

OBJS := vmufs.o

SUBDIRS :=

include $(KOS_BASE)/Makefile.prefab



