#if !defined(AFX__STOCKTICKERMFC_H__F3E3A931_98D1_11D0_944D_00A0C903487E__INCLUDED_)
#define AFX__STOCKTICKERMFC_H__F3E3A931_98D1_11D0_944D_00A0C903487E__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CStockTickerCtrl wrapper class

class CStockTickerCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CStockTickerCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x50D64433, 0x8EA4, 0x11D0, { 0x94, 0x3E, 0x00, 0xA0, 0xC9, 0x03, 0x48, 0x7E} };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

	BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

	void LoadControl(CArchive& ar) {};
	void WriteControl(CArchive& ar);
	void Serialize(CArchive& ar);

// Attributes
public:
	OLE_COLOR   GetBackColor();
	void        SetBackColor(OLE_COLOR);
	COleFont    GetFont();
	void        SetFont(LPDISPATCH);
	OLE_COLOR   GetForeColor();
	void        SetForeColor(OLE_COLOR);
	short       GetUpdateInterval();
	void        SetUpdateInterval(short);
	short       GetTickerSpeed();
	void        SetTickerSpeed(short);

// Operations
public:
	void        AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__STOCKTICKERMFC_H__F3E3A931_98D1_11D0_944D_00A0C903487E__INCLUDED_)
