#------------------------------------------------------------------------------
#k2logo.mak
#------------------------------------------------------------------------------

PROJECT =	k2logo

PROJECT_SRC	= \
		DISPSTR.C\
		KMLOGO.C\
		MAIN.C\
		sbinit.c\
		TEXCHAR.C\
		TEXLOGO.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
