# KallistiOS ##version##
#
# loadable/programs/net Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.3 2003/07/31 00:55:41 bardtx Exp $

DIRS = chargen httpd telnetd debughost startnet netiohost # netcfg

include ../../Makefile.subdirs

