/*++

Copyright (c) 1996  Microsoft Corporation

Module Name:

    SspsErr

Abstract:

    This header file describes the error codes that are generated by
	the Microsoft Smartcard Service Provider (SSP).

Author:

    Michael Gallagher (a-mgalla) 10/21/1996

Environment:

    Win32

Revision History:

	Mike Gallagher (a-mgalla) 12/19/1996

Notes:

--*/


#ifndef __SSPSERR_H__
#define __SSPSERR_H__

/////////////////////////////////////////////////////////////////////////////
//
// Includes
//

#include "scarderr.h"


/////////////////////////////////////////////////////////////////////////////

#endif  // __SSPSERR_H__
