#------------------------------------------------------------------------------
#nowload.mak
#------------------------------------------------------------------------------

PROJECT =	nowload

PROJECT_SRC	= \
		DISPMSG.C\
		MSGDATA.C\
		njloop.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
