# KallistiOS ##version##
#
# arch/dreamcast/util/Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/06/19 04:21:00 bardtx Exp $

BUILD_TARGET=loadable/libkos

OBJS = vmu_pkg.o screenshot.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


