/*
 * NOTE:  This file is a 16-bit modification of ianimal.h.
 * This is not generated by MIDL directly.
 */

#ifndef __ianim16_h__
#define __ianim16_h__


DECLARE_INTERFACE_(IAnimal, IUnknown)
    {
    //IUnknown members
    STDMETHOD(QueryInterface) (THIS_ REFIID, PPVOID) PURE;
    STDMETHOD_(ULONG,AddRef)  (THIS) PURE;
    STDMETHOD_(ULONG,Release) (THIS) PURE;

    STDMETHOD(Eat)(THIS_ LPTSTR, LPTSTR, short) PURE;
    STDMETHOD(Sleep)(THIS_ short FAR *) PURE;
    STDMETHOD(Procreate)(short FAR *) PURE;
    STDMETHOD(WhatKindOfAnimal)(IID FAR *) PURE;
    };

typedef IAnimal *PANIMAL, FAR *LPANIMAL;

#endif //__ianim16_h__
