# KallistiOS ##version##
#
# kernel/fs/Makefile
# Copyright (C)2000,2001,2002,2003 Dan Potter
#   
# $Id: Makefile,v 1.4 2003/06/19 04:29:00 bardtx Exp $

OBJS = fs.o fs_pty.o fs_romdisk.o elf.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab

