// FishTankLevelGetter.idl : IDL source for FishTankLevelGetter.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (FishTankLevelGetter.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	
	[
		object,
		uuid(7F0DFAA2-F56D-11D0-A980-0020182A7050),
		helpstring("ILevelGetter Interface"),
		pointer_default(unique)
	]
	interface ILevelGetter : IUnknown
	{
		HRESULT GetLowestPossibleSafeLevel([out, retval] long* plLowestSafeLevel);
		HRESULT GetHighestPossibleSafeLevel([out, retval]                                    long* plHighestSafeLevel);
		HRESULT GetCurrentLevel([out, retval] long* plCurrentLevel);
		HRESULT GetTextMessage([out, retval] BSTR* ppbstrMessage);
	};


[
	uuid(7F0DFA91-F56D-11D0-A980-0020182A7050),
	version(1.0),
	helpstring("FishTankLevelGetter 1.0 Type Library")
]
library FISHTANKLEVELGETTERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	
	[
		uuid(7F0DFAA3-F56D-11D0-A980-0020182A7050),
		helpstring("LevelGetter Class")
	]
	coclass LevelGetter
	{
		[default] interface ILevelGetter;
	};

};
