# KallistiOS ##version##
#
# addons/libtremor Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2003/02/27 04:25:42 bardtx Exp $

TARGET = libtremor.a
OBJS  =
SUBDIRS = xiph kos
LIB_OBJS = build/*.o
LOCAL_CLEAN = build/*.o build/*.a

include ../Makefile.prefab
