# KallistiOS ##version##
#
# examples/dreamcast/network/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.5 2002/06/11 06:14:39 bardtx Exp $

all:
	$(KOS_MAKE) -C basic
	$(KOS_MAKE) -C httpd
#	$(KOS_MAKE) -C dcload-ip-lwip-test

clean:
	$(KOS_MAKE) -C basic clean
	$(KOS_MAKE) -C httpd clean
#	$(KOS_MAKE) -C dcload-ip-lwip-test clean
		
dist:
	$(KOS_MAKE) -C basic dist
	$(KOS_MAKE) -C httpd dist
#	$(KOS_MAKE) -C dcload-ip-lwip-test dist


