# KallistiOS ##version##
#
# examples/dreamcast/sound/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/07/17 04:03:56 bardtx Exp $

all:
	$(KOS_MAKE) -C ghettoplay-vorbis
	$(KOS_MAKE) -C hello-ogg
	$(KOS_MAKE) -C cdda

clean:
	$(KOS_MAKE) -C ghettoplay-vorbis clean
	$(KOS_MAKE) -C hello-ogg clean
	$(KOS_MAKE) -C cdda clean
		
dist:
	$(KOS_MAKE) -C ghettoplay-vorbis dist
	$(KOS_MAKE) -C hello-ogg dist
	$(KOS_MAKE) -C cdda dist


