#------------------------------------------------------------------------------
#sg_gd3.mak
#------------------------------------------------------------------------------

PROJECT =	sg_gd3

PROJECT_SRC	= \
		njloop.c\
		req.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
