# KallistiOS ##version##
#
# examples/dreamcast/vmu/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/02/24 06:20:12 bardtx Exp $

all:
	$(KOS_MAKE) -C vmu_pkg

clean:
	$(KOS_MAKE) -C vmu_pkg clean
		
dist:
	$(KOS_MAKE) -C vmu_pkg dist


