# KallistiOS ##version##
#
# arch/dreamcast/hardware/Makefile
# Copyright (C)2000,2001,2002,2003 Dan Potter
#
# $Id: Makefile,v 1.13 2003/06/19 04:23:42 bardtx Exp $

OBJS = asic.o g2bus.o hardware.o vblank.o

include $(KOS_BASE)/Makefile.prefab



