# KallistiOS ##version##
#
# arch/dreamcast/hardware/Makefile
# Copyright (C)2003 Dan Potter
#
# $Id: Makefile,v 1.1 2003/06/19 04:20:59 bardtx Exp $

BUILD_TARGET=loadable/libkos

# BIOS services
OBJS += biosfont.o cdrom.o flashrom.o

# Sound
OBJS += spu.o spudma.o

# Video-related
OBJS += video.o

# CPU-related
OBJS += sq.o

SUBDIRS = pvr modem

include $(KOS_BASE)/Makefile.prefab



