	//
	// IPerfmonObject
	//
	[
		object,
		uuid(3DBD6FB0-FFA7-11d0-9F8C-400004491341),
		dual,
		helpstring("IPerfmonObject Interface"),
		pointer_default(unique)
	]
	interface IPerfmonObject : IDispatch
	{
		import "oaidl.idl";
		[helpstring("Returns the object name.  This is the name displayed in perfmon")] 
		HRESULT GetName([out, retval] BSTR *pName);

		[helpstring("Returns the object's help text.  This is the explain text displayed in perfmon")] 
		HRESULT GetHelp([out, retval] BSTR *pHelp);

		[helpstring("Returns the object's index.")] 
		HRESULT GetIndex([out, retval] long *pIndex);

		[helpstring("Returns the number of counters.")] 
		HRESULT GetNumCounters([out, retval] long *pNumCounters);

		[helpstring("Returns an enumeration of the counters for this object")] 
		HRESULT GetCounters([out, retval] IUnknown **pCounters);
	};

	//
	// IPerfmonCounter
	//
	[
		object,
		uuid(3DBD6FB1-FFA7-11d0-9F8C-400004491341),
		dual,
		helpstring("IPerfmonCounter Interface"),
		pointer_default(unique)
	]
	interface IPerfmonCounter : IDispatch
	{
		import "oaidl.idl";
		[helpstring("Collects data for this counter")] 
		HRESULT Collect([out, retval] VARIANT *pVariant);

		[helpstring("Returns the Counter name.  This is the name displayed in perfmon")] 
		HRESULT GetName([out, retval] BSTR *pName);

		[helpstring("Returns the counter's help text.  This is the explain text displayed in perfmon")] 
		HRESULT GetHelp([out, retval] BSTR *pHelp);

		[helpstring("Returns the counter's index.")] 
		HRESULT GetIndex([out, retval] long *pIndex);

		[helpstring("Return the data type of the counter.")] 
		HRESULT GetDataType([out, retval] short *pDataType);

	};