# KallistiOS ##version##
#
# utils/isotest/Makefile
# (c)2000 Dan Potter
#   
# $Id: Makefile,v 1.1.1.1 2001/09/26 07:05:01 bardtx Exp $

all: isotest

isotest: isotest.c
	gcc -g -o isotest isotest.c

