##-----------------------------------------------------------------------------
##
##	FILE:		amabuse.mak
##
##	DESC:		Makefile for amabuse sample
##
##	HISTORY:	2000.01.xx	Reworked samples/boilerplates for R10 release.
##
##-----------------------------------------------------------------------------

PROJECT			= amplaymidi

PROJECT_SRC		=\
				main.c\
				sbinit.c\
				amplaymidi.c\
				bpprintf.c\
				bpacsetup.c\
				bpamsetup.c\

SYSTEM_LIBS		=\
				audio64

OPTIMIZE		= 0

#COMPILER		= SHC
GFXLIB			= NINJA
OUTPUT			= ELF

DEBUG			= TRUE
#LIST			= TRUE

include $(KATANA_ROOT)\sample\dc.inc
