# KallistiOS ##version##
#
# libjpeg Makefile
#   
# $Id: Makefile,v 1.4 2003/02/27 04:25:40 bardtx Exp $

TARGET = libjpeg.a
OBJS = 	jcapimin.o jcapistd.o jccoefct.o jccolor.o jcdctmgr.o jchuff.o \
	jcinit.o jcmainct.o jcmarker.o jcmaster.o jcomapi.o jcparam.o \
        jcphuff.o jcprepct.o jcsample.o jctrans.o jdapimin.o jdapistd.o \
        jdatadst.o jdatasrc.o jdcoefct.o jdcolor.o jddctmgr.o jdhuff.o \
        jdinput.o jdmainct.o jdmarker.o jdmaster.o jdmerge.o jdphuff.o \
        jdpostct.o jdsample.o jdtrans.o jerror.o jfdctflt.o \
        jidctflt.o jidctred.o jquant1.o \
        jquant2.o jutils.o jmemmgr.o
OBJS +=	jmemnobs.o
OBJS += kos_img.o

include ../Makefile.prefab


