0001
 (I) Character combination "@" in comment
0002
 (I) No declarator
0003
 (I) Unreachable statement
0004
 (I) Constant as condition
0005
 (I) Precision lost
0006
 (I) Conversion in argument
0008
 (I) Conversion in return
0010
 (I) Elimination of needless expression
0011
 (I) Used before set symbol : "@"
0012
 (I) Unused variable "@"
0015
 (I) No return value
0100
 (I) Function "@" not optimized
0200
 (I) No prototype function
1000
 (W) Illegal pointer assignment
1001
 (W) Illegal comparison in "@"
1002
 (W) Illegal pointer for "@"
1005
 (W) Undefined escape sequence
1007
 (W) Long character constant
1008
 (W) Identifier too long
1010
 (W) Character constant too long
1012
 (W) Floating point constant overflow
1013
 (W) Integer constant overflow
1014
 (W) Escape sequence overflow
1015
 (W) Floating point constant underflow
1016
 (W) Argument mismatch
1017
 (W) Return type mismatch
1019
 (W) Illegal constant expression
1020
 (W) Illegal constant expression of "-"
1021
 (W) Register saving pragma conflicts in interrupt function "@"
1022
 (W) First operand of "@" is not lvalue
1023
 (W) Can not convert japanese code "@" to output type
1024
 (W) Out of float
1200
 (W) Division by floating point zero
1201
 (W) Ineffective floating point operation
1300
 (W) Command parameter specified twice
1400
 (W) Function "@" in #pragma inline is not expanded
1401
 (W) "case=table" option ignored by switch
1500
 (W) EC++ does not support "@"
2000
 (E) Illegal preprocessor keyword
2001
 (E) Illegal preprocessor syntax
2002
 (E) Missing ","
2003
 (E) Missing ")"
2004
 (E) Missing ">"
2005
 (E) Cannot open include file "@"
2006
 (E) Multiple #define's
2008
 (E) Processor directive #elif mismatches
2009
 (E) Processor directive #else mismatches
2010
 (E) Macro parameters mismatch
2011
 (E) Line too long
2012
 (E) Keyword as a macro name
2013
 (E) Processor directive #endif mismatches
2014
 (E) Missing #endif
2016
 (E) Preprocessor constant expression too complex
2017
 (E) Missing "
2018
 (E) Illegal #line
2019
 (E) File name too long
2020
 (E) System identifier "@" redefined
2100
 (E) Multiple storage classes
2101
 (E) Address of register
2102
 (E) Illegal type combination
2103
 (E) Bad self reference structure
2104
 (E) Illegal bit field width
2105
 (E) Incomplete tag used in declaration
2106
 (E) Extern variable initialized
2107
 (E) Array of function
2108
 (E) Function returning array
2109
 (E) Illegal function declaration
2110
 (E) Illegal storage class
2111
 (E) Function as a member
2112
 (E) Illegal bit field
2113
 (E) Bit field too wide
2114
 (E) Multiple variable declarations
2115
 (E) Multiple tag declarations
2117
 (E) Empty source program
2118
 (E) Prototype mismatch "@"
2119
 (E) Not a parameter name "@"
2120
 (E) Illegal parameter storage class
2121
 (E) Illegal tag name
2122
 (E) Bit field width 0
2123
 (E) Undefined tag name
2124
 (E) Illegal enum value
2125
 (E) Function returning function
2126
 (E) Illegal array size
2127
 (E) Missing array size
2128
 (E) Illegal pointer declaration for "*"
2129
 (E) Illegal initializer type
2130
 (E) Initializer should be constant
2131
 (E) No type nor storage class
2132
 (E) No parameter name
2133
 (E) Multiple parameter declarations
2134
 (E) Initializer for parameter
2135
 (E) Multiple initialization
2136
 (E) Type mismatch
2137
 (E) Null declaration for parameter
2138
 (E) Too many initializers
2139
 (E) No parameter type
2140
 (E) Illegal bit field
2141
 (E) Struct has no member name 
2142
 (E) Illegal void type
2143
 (E) Illegal static function
2144
 (E) Type mismatch
2145
 (E) Const/volatile specified for incomplete type
2200
 (E) Index not integer
2201
 (E) Cannot convert parameter "@"
2202
 (E) Number of parameters mismatch
2203
 (E) Illegal member reference for "."
2204
 (E) Illegal member reference for "->"
2205
 (E) Undefined member name
2206
 (E) Modifiable lvalue required for "@"
2207
 (E) Scalar required for "!"
2208
 (E) Pointer required for "*"
2209
 (E) Arithmetic type required for "@"
2210
 (E) Integer required for "~"
2211
 (E) Illegal sizeof
2212
 (E) Illegal cast
2213
 (E) Arithmetic type required for "@"
2214
 (E) Integer required for "@"
2215
 (E) Illegal type for "+"
2216
 (E) Illegal type for parameter
2217
 (E) Illegal type for "-"
2218
 (E) Scalar required
2219
 (E) Type not compatible in "? :"
2220
 (E) Modifiable lvalue required for "@"
2221
 (E) Illegal type for "@"
2222
 (E) Type not compatible for "="
2223
 (E) Incomplete tag used in expression
2224
 (E) Illegal type for assign
2225
 (E) Undeclared name "@"
2226
 (E) Scalar required for "@"
2227
 (E) Illegal type for equality
2228
 (E) Illegal type for comparison
2230
 (E) Illegal function call
2231
 (E) Address of bit field
2232
 (E) Illegal type for "@"
2233
 (E) Illegal array reference
2234
 (E) Illegal typedef name reference
2235
 (E) Illegal cast
2236
 (E) Illegal cast in constant
2237
 (E) Illegal constant expression
2238
 (E) Lvalue or function type required for "&"
2300
 (E) Case not in switch
2301
 (E) Default not in switch
2302
 (E) Multiple labels
2303
 (E) Illegal continue
2304
 (E) Illegal break
2305
 (E) Void function returns value
2306
 (E) Case label not constant
2307
 (E) Multiple case labels
2308
 (E) Multiple default labels
2309
 (E) No label for goto
2310
 (E) Scalar required
2311
 (E) Integer required
2312
 (E) Missing (
2313
 (E) Missing ;
2314
 (E) Scalar required
2316
 (E) Illegal type for return value
2400
 (E) Illegal character "@"
2401
 (E) Incomplete character constant
2402
 (E) Incomplete string
2403
 (E) EOF in comment
2404
 (E) Illegal character code "@"
2405
 (E) Null character constant
2407
 (E) Incomplete logical line
2408
 (E) Comment nest too deep
2500
 (E) Illegal token "@"
2501
 (E) Division by zero
2600
 (E) "@"
2650
 (E) Invalid pointer reference
2700
 (E) Function "@" in #pragma interrupt already declared
2701
 (E) Multiple interrupt for one function
2702
 (E) Multiple #pragma interrupt options
2703
 (E) Illegal #pragma interrupt declaration
2704
 (E) Illegal reference to interrupt function
2705
 (E) Illegal parameter in interrupt function
2706
 (E) Missing parameter declaration in interrupt function
2707
 (E) Parameter out of range in interrupt function
2708
 (E) Illegal option declared in #pragma asm
2709
 (E) Illegal section name declaration
2710
 (E) Section name too long
2711
 (E) Section name table overflow
2712
 (E) GBR based displacement overflow
2713
 (E) Illegal #pragma interrupt function type 
2800
 (E) Illegal parameter number in in-line function
2801
 (E) Illegal parameter type in in-line function
2802
 (E) Parameter out of range in in-line function
2803
 (E) Invalid offset value in in-line function
2804
 (E) Illegal in-line function
2805
 (E) Function "@" in #pragma inline/inline_asm already declared
2806
 (E) Multiple #pragma for one function
2807
 (E) Illegal #pragma inline/inline_asm declaration
2808
 (E) Illegal option for #pragma inline_asm
2809
 (E) Illegal #pragma inline/inline_asm function type
2810
 (E) Global variable "@" in #pragma gbr_base/gbr_base1 already declared
2811
 (E) Multiple #pragma for one global variable
2812
 (E) Illegal #pragma gbr_base/gbr_base1 declaration
2813
 (E) Illegal #pragma gbr_base/gbr_base1 global variable type
2814
 (E) Function "@" in #pragma noregsave/noregalloc/regsave already declared
2815
 (E) Illegal #pragma noregsave/noregalloc/regsave declaration
2816
 (E) Illegal #pragma noregsave/noregalloc/regsave function type
2817
 (E) Symbol "@" in #pragma abs16 already declared 
2818
 (E) Multiple #pragma for one symbol
2819
 (E) Illegal #pragma abs16 declaration
2820
 (E) Illegal #pragma abs16 symbol type
2821
 (E) Global variable "@" in #pragma global_register already declared
2822
 (E) Illegal register "@" in #pragma global_register
2823
 (E) Illegal #pragma global_register declaration
2824
 (E) Illegal #pragma global_register type
2825
 (E) Illegal #pragma aligndata declaration
2826
 (E) Illegal #pragma aligndata variable type
2827
 (E) Global variable "@" in #pragma aligndata already declared
3000
 (F) Statement nest too deep
3001
 (F) Block nest too deep
3002
 (F) #if nest too deep
3006
 (F) Too many parameters
3007
 (F) Too many macro parameters
3008
 (F) Line too long
3009
 (F) String literal too long
3010
 (F) Processor directive #include nest too deep
3011
 (F) Macro expansion nest too deep
3012
 (F) Too many function definitions
3013
 (F) Too many switches
3014
 (F) For nest too deep
3015
 (F) Symbol table overflow
3016
 (F) Internal label overflow
3017
 (F) Too many case labels
3018
 (F) Too many goto labels
3019
 (F) Cannot open source file "@"
3020
 (F) Source file input error "@"
3021
 (F) Memory overflow
3022
 (F) Switch nest too deep
3023
 (F) Type nest too deep
3024
 (F) Array dimension too deep
3025
 (F) Source file not found
3026
 (F) Expression too complex
3027
 (F) Source file too complex
3028
 (F) Source line number overflow
3029
 (F) Physical line overflow
3030
 (F) Too many compound statements
3031
 (F) Data size overflow
3033
 (F) Symbol table overflow
3100
 (F) Misaligned pointer access
3201
 (F) Object size overflow
3202
 (F) Too many source lines for debug
3203
 (F) Assembly source line too long
3204
 (F) Illegal stack access
3300
 (F) Cannot open internal file
3301
 (F) Cannot close internal file
3302
 (F) Cannot input internal file
3303
 (F) Cannot output internal file
3304
 (F) Cannot delete internal file
3305
 (F) Invalid command parameter "@"
3306
 (F) Interrupt in compilation
3307
 (F) Compiler version mismatch
3308
 (F) Cannot create file "@"
3320
 (F) Command parameter buffer overflow
3321
 (F) Illegal environment variable
0

/*------------------------------------------------------*/
/* SH SERIES C Compiler Ver. 1.0                        */
/* Copyright (c) 1992 Hitachi,Ltd.                      */
/* Licensed material of Hitachi,Ltd.                    */
/*------------------------------------------------------*/
