5001
 (W) Linkage specification ignored for 'static' functions and objects
6001
 (E) Overloaded function "@" cannot specify #pragma function
6002
 (E) Preprocessing numerical token is not floating constant value or integer constant value
6101
 (E) Illegal storage class 'auto'
6102
 (E) Illegal storage class 'register'
6103
 (E) 'static' keyword must be applied to objects, functions and anonymous unions
6104
 (E) Function declaration "@" cannot have 'static' storage in a block
6105
 (E) Static linkage specifications for "@" must agree
6106
 (E) Illegal storage class 'extern'
6108
 (E) Inline member function "@" must be declared before it is called
6109
 (E) Illegal function specifier 'virtual'
6110
 (E) Illegal 'typedef' declaration in function definition "@"
6111
 (E) 'typedef' "@" cannot re-define other types in the same scope
6112
 (E) Cannot specify 'typedef' "@" after 'enum'
6114
 (E) Integral type data is not assigned to an enumeration
6116
 (E) Undefined linkage-specification "@"
6117
 (E) Multiple linkage-specification "@"
6118
 (E) 'static' function "@" with linkage-specification
6119
 (E) Multiple 'C' linkage overloaded function "@"
6120
 (E) Illegal 'void &' type
6123
 (E) Cannot specify a reference to &, to bit-fields, to array or to pointer type
6124
 (E) Initial value required for declaration & "@"
6128
 (E) New type defined in a return type of a function or in a parameter
6129
 (E) Non-static members or 'auto' variables cannot be used as default parameter
6130
 (E) Default parameter re-defined in function "@"
6131
 (E) Non-default parameters found following default parameters
6133
 (E) Overloaded operators cannot have default parameters
6139
 (E) Overloaded functions "@" have the same type of parameters except & type
6140
 (E) Functions "@" have the same type of parameters except const/volatile type
6141
 (E) Functions "@" have the same type of parameters except return type
6142
 (E) Cannot overload function "@"
6143
 (E) Operator overloaded function "@" does not have correct parameters
6144
 (E) Operator overloaded function "=" is not a nonstatic member function
6145
 (E) Operator overloaded function "( )" is not a nonstatic member function
6146
 (E) Operator overloaded function "[ ]" is not a nonstatic member function
6147
 (E) Operator overloaded function "->" returns illegal type value
6148
 (E) Operator overloaded function "->" is not a nonstatic member function
6149
 (E) The second parameter of the postfix operator function should have type int
6150
 (E) 'const' object should have an initial value
6151
 (E) 'friend' should be specified in a class declaration
6152
 (E) 'friend' keyword specified twice
6153
 (E) 'inline' keyword specified twice
6154
 (E) 'virtual' keyword specified twice
6155
 (E) 'inline' must be specified for functions
6156
 (E) Parameters cannot have 'inline' specifier
6157
 (E) Cannot specify 'inline' and 'extern' together
6158
 (E) Object "@" initialized with { } format
6159
 (E) 'typedef' cannot specify 'friend'
6162
 (E) Cannot declare 'typedef' name qualified by a class
6163
 (E) Missing the number of operator function parameters
6165
 (E) Operator member function cannot specify 'static'
6166
 (E) Operator function or conversion function has function type
6167
 (E) Conversion function should be a nonstatic member function
6169
 (E) A destructor should be a function type
6170
 (E) Non-member functions cannot specify 'const' or 'volatile'
6171
 (E) Declarations qualified by a class cannot specify storage class specifier
6172
 (E) Cannot declare parameter declarations qualified by a class
6203
 (E) Ambiguous name "@"
6209
 (E) Array "@" does not have dimension size
6210
 (E) Member declarator be ommited
6211
 (E) Non-virtual function "@" cannot specify "=0"
6212
 (E) Member "@" cannot have the same name of that class
6213
 (E) Static member function cannot access "@"
6219
 (E) Static data member "@" cannot exist in a local class
6221
 (E) Union "@" cannot have virtual functions
6222
 (E) Union "@" cannot have base classes
6223
 (E) Union "@" cannot be a base class
6224
 (E) Union member cannot have a constructor, destructor or class with a user defined operator =( )
6225
 (E) Union "@" cannot have static data members
6227
 (E) Anonymous union must specify 'static'
6228
 (E) Anonymous union cannot have private and protected members
6229
 (E) Anonymous union cannot have member functions
6233
 (E) Nested class declaration cannot access "@"
6234
 (E) "@" cannot be specified in a local class declaration
6236
 (E) Member function "@" should be defined in the local class declaration
6240
 (E) Member "@" defined more than once
6241
 (E) Undeclared member "@"
6242
 (E) "@" declared multiple
6243
 (E) Undeclared base class "@"
6244
 (E) Base class "@" defined more than once in the derived class declaration
6246
 (E) Virtual base class "@" casted to the derived class
6248
 (E) Returning type mismatch in virtual function "@"
6250
 (E) Illegal 'static' virtual function "@"
6251
 (E) Cannot create abstract class object "@"
6252
 (E) Class object has ambigous virtual functions
6254
 (E) Implicit pure virtual function "@" call
6256
 (E) "@" is not a member of the class
6263
 (E) "@" should be defined as a class or a struct
6267
 (E) Illegal declaration "@" in type-specifier
6268
 (E) "@" cannot have parameters and return value
6269
 (E) Ambiguous user defined conversion
6270
 (E) Destructor "@" cannot have parameters and return value
6271
 (E) Constructor and destructor cannot have 'const', 'volatile' or 'static' keywords
6272
 (E) Constructor and destructor "@" do not have addresses
6274
 (E) The first parameter type of operator new() should be 'size_t'
6275
 (E) The return type of operator new() should be 'void *'
6276
 (E) The first parameter type of operator delete() should be 'void *'
6277
 (E) The return type of operator delete() should be 'void'
6278
 (E) Operator delete() function cannot be overloaded
6280
 (E) The second parameter type of operator delete() should be 'size_t'
6281
 (E) Illegal virtual operator new() or delete() function
6282
 (E) Default constructor required
6283
 (E) Class "@" requires a constructor
6284
 (E) Undefined class member "@"
6285
 (E) Multiple implicit conversion
6286
 (E) 'public' copy constructor "@" required
6287
 (E) Illegal nonstatic 'const' array initialization
6288
 (E) Constructors cannot initialize indirect base classes or derived members
6289
 (E) Cannot generate default assignment operator
6290
 (E) Cannot generate default copy constructor "@"
6291
 (E) Cannot assign "@"
6292
 (E) Cannot access private member "@"
6293
 (E) Cannot access protected member "@"
6294
 (E) Illegal access declaration "@"
6296
 (E) Cannot change the access control of overloaded function "@"
6297
 (E) Cannot change the access control of redefined member "@"
6298
 (E) 'friend' declaration syntax error
6303
 (E) Cannot access base class "@"
6304
 (E) Cannot define 'friend' data members
6305
 (E) Illegal pure virtual function specifier
6306
 (E) Cannot access class "@" member
6307
 (E) Cannot access base class member "@"
6308
 (E) Constructors cannot have return type
6310
 (E) Cannot define class member "@"
6311
 (E) Illegal constructor/destructor declaration
6313
 (E) Cannot declare nonstatic data member "@"
6314
 (E) Illegal data member initializer
6401
 (E) 'this' should be referred to in a nonstatic member function
6402
 (E) "@" does not exist in this file scope
6404
 (E) "@" is not a member
6407
 (E) The type of the second operand of '?:' is different from the third operand
6408
 (E) Base class objects cannot be assigned to derived class objects
6409
 (E) '?:' operands should have integral types
6417
 (E) Illegal type conversion
6421
 (E) Invalid 'new' operand
6425
 (E) An array cannot be initialized in a 'new' operator
6428
 (E) Invalid 'delete' operand
6430
 (E) Cannot convert an object or data to a class object
6431
 (E) Cannot convert a virtual base class to a derived class
6432
 (E) Illegal explicit type conversion
6433
 (E) '->*' operands type mismatch
6434
 (E) The second operand of '->*' and '.*' operator should be a pointer to member of a class
6435
 (E) '.*' operands type mismatch
6437
 (E) Unary '&' operand require a qualified name
6441
 (E) 'typedef' "@" used as a constructor or a destructor
6442
 (E) Cannot refer to undefined class
6446
 (E) Ambiguous overloaded function call
6449
 (E) Ambiguous function name referred to
6450
 (E) Illegal function pointer conversion
6451
 (E) Undeclared function call
6452
 (E) Pointer-to-Member cannot be used as an operand of a function call
6503
 (E) Statements is required in selection statements or iteration statements
6504
 (E) Declaration with initialization is not executed
6508
 (E) Illegal conditional expression
6513
 (E) Illegal jump
6514
 (E) "@" is not supported
6515
 (E) EC++ useless keyword "@"
7001
 (F) Too many identifiers
0

/*------------------------------------------------------*/
/* SH C++ Compiler Ver. 1.1                             */
/* Copyright (c) 1996, 1997 Hitachi,Ltd.                */
/* Licensed material of Hitachi,Ltd.                    */
/*------------------------------------------------------*/
