#------------------------------------------------------------------------------
# Materials.mak
#------------------------------------------------------------------------------

PROJECT =	Materials

PROJECT_SRC	= \
		Data.c\
		KMBump.c\
		KMLight.c\
		KMMatrix.c\
		KMMisc.c\
		KMShell.c\
		KMTexture.c\
		KMTimer.c\
		KMTransform.c\
		Materials.c\
		sbinit.c\
		KMPrint3D.c\
		VQCalc.c\

OPTIMIZE =	0

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
