# KallistiOS ##version##
#
# examples/dreamcast/tsunami/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/09/09 08:47:33 bardtx Exp $

all:
	$(KOS_MAKE) -C font
	$(KOS_MAKE) -C banner

clean:
	$(KOS_MAKE) -C font clean
	$(KOS_MAKE) -C banner clean
		
dist:
	$(KOS_MAKE) -C font dist
	$(KOS_MAKE) -C banner dist


