#------------------------------------------------------------------------------
#k2marble.mak
#------------------------------------------------------------------------------

PROJECT =	k2marble

PROJECT_SRC	= \
		BARK.C\
		DISPSTR.C\
		KMMARBLE.C\
		MAIN.C\
		MARBLE.C\
		MARBLE2.C\
		sbinit.c\
		SOJ_TOOL.C\
		TEXCHAR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
