# KallistiOS ##version##
#
# arch/dreamcast/hardware/modem/Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/05/23 02:04:42 bardtx Exp $

OBJS = mdata.o mintr.o modem.o msegbuf.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab

