#------------------------------------------------------------------------------
# MSTSTL.mak
#------------------------------------------------------------------------------

PROJECT =       MSLSTL

PROJECT_SRC	= \
                main.cpp\
		sbinit.c\

OPTIMIZE =      1

#COMPILER =     GNU
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
