#------------------------------------------------------------------------------
#teapot.mak
#------------------------------------------------------------------------------

PROJECT =	teapot

PROJECT_SRC	= \
		model.c\
		njloop.c\
		sbinit.c\
		t009.c\
		test.c\
		global32.S\
		global32.src\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	BIN

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
