# This is the Windows version of the TP Installation makefile.
all: tpsetup.exe

OPTS = -c -AS -G2sw -Zipe -W2 -Od $(DEFINES)
CC = cl $(OPTS)

OBJS = install.obj

install.obj: install.c install.h
    $(CC) $*.c

install.res: install.rc install.h dialogs.h
    rc -r $(DEFINES) install.rc

tpsetup.exe: $(OBJS) install.lnk install.res install.def install.rc
    link @install.lnk
    rc install.res tpsetup.exe
