#------------------------------------------------------------------------------
#vib01.mak
#------------------------------------------------------------------------------

PROJECT =	vib01

PROJECT_SRC	= \
		njloop.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
