#------------------------------------------------------------------------------
#gun3.mak
#------------------------------------------------------------------------------

PROJECT =	gun3

PROJECT_SRC	= \
		GUN.C\
		njloop.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
