USE_ODBC=1
Proj = AdmnDemo

!include <BkOffice.Mak>

All: $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(@R).Obj $(@D)\Dialogs.Obj $(@D)\ErrCheck.Obj \
                       $(@D)\Execute.Obj $(@D)\Info.Obj $(@D)\Ini.Obj \
                       $(@D)\Menu.Obj $(@D)\Results.Obj $(@D)\Standard.Obj $(@R).Res
