# KallistiOS ##version##
#
# kernel/libc/koslib/Makefile
# Copyright (C)2004 Dan Potter
#

# In here we have pieces of the KOS libc that are either too custom or too
# useful in the context of KOS to go with the Newlib defaults.

OBJS = abort.o byteorder.o memset2.o memset4.o memcpy2.o memcpy4.o \
	assert.o dbglog.o malloc.o crtbegin.o crtend.o atexit.o \
	opendir.o readdir.o closedir.o rewinddir.o scandir.o seekdir.o \
	telldir.o usleep.o inet_addr.o realpath.o getcwd.o chdir.o mkdir.o \
	creat.o sleep.o rmdir.o rename.o

include $(KOS_BASE)/Makefile.prefab
