# KallistiOS ##version##
#
# arch/ps2 Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.3 2002/11/06 08:36:40 bardtx Exp $
	
SUBDIRS=kernel sbios fs

include $(KOS_BASE)/Makefile.rules

all: subdirs
clean: clean_subdirs
