######################################################################
#                                                                    #
#                   MAKEFILE       Version 0.50.01                   #
#                                                                    #
######################################################################



MAKEPRE  = $(SHINOBI_DIR)\LIB\MAKEPRE
MAKEFILE = .\MAKEFILE
MAKEPOST = $(SHINOBI_DIR)\LIB\MAKEPOST
MAKEUSER = .\MAKEUSER

MAKEFILES = $(MAKEFILE) $(MAKEPRE) $(MAKEPOST) $(MAKEUSER)

!include	$(MAKEPRE)
!include	$(MAKEUSER)
!include	$(MAKEPOST)

#EOF#
