all: dbg rtl

clean dbg rtl:
    cd d3dim
    nmake $(@B)
    cd ..\ddraw
    nmake $(@B)
    cd ..\demos
    nmake $(@B)
    cd ..\dinput
    nmake $(@B)
    cd ..\dmusic
    nmake $(@B)
    cd ..\dplay
    nmake $(@B)
    cd ..\dshow
    nmake $(@B)
    cd ..\dsound
    nmake $(@B)
    cd ..\gdrom
    nmake $(@B)
    cd ..\ime
    nmake $(@B)
    cd ..\ie
    nmake $(@B)
    cd ..\mapledevices
    nmake $(@B)
    cd ..\midi
    nmake $(@B)
    cd ..\misc
    nmake $(@B)
    cd ..
