
cpp_quote("#if 0")
#if defined(__midl)
    /* MIDL 2.0 definitions */
    typedef short *REFSHORT;
#else
    /* MIDL 1.1 definitions */
    typedef short REFSHORT;
#endif
cpp_quote("#endif // 0")

cpp_quote("#if defined(__cplusplus)")

cpp_quote("#ifndef _REFSHORT_DEFINED")
cpp_quote("#define _REFSHORT_DEFINED")
cpp_quote("#define REFSHORT             short &")
cpp_quote("#endif // !_REFSHORT_DEFINED")

cpp_quote("#else // !__cplusplus")

cpp_quote("#ifndef _REFSHORT_DEFINED")
cpp_quote("#define _REFSHORT_DEFINED")
cpp_quote("#define REFSHORT             short * ")
cpp_quote("#endif // !_REFSHORT_DEFINED")

cpp_quote("#endif // !__cplusplus")
