# KallistiOS ##version##
#
# loadable/programs Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.5 2003/08/02 23:07:37 bardtx Exp $

DIRS = kosh net splash hello # ghettoplay-vorbis gltest

include ../Makefile.subdirs

