#------------------------------------------------------------------------------
#playvid.mak
#------------------------------------------------------------------------------

PROJECT =	playvid

PROJECT_SRC	= \
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	BIN

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
