# KallistiOS ##version##
#
# modules Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.2 2003/07/15 07:55:01 bardtx Exp $

DIRS = fs_iso9660 fs_ramdisk fs_vmu fs_dcload_ip

include ../../Makefile.subdirs

