#ifndef _DBSERVER_INCLUDE
#define _DBSERVER_INCLUDE

import "unknwn.idl";
import "..\interface\refshort.idl";

[object, uuid(30DF3432-0266-11cf-BAA6-00AA003E0EED), pointer_default(unique)]
interface IDB : IUnknown {
  // Interfaces
	  	// Interface for data access
		HRESULT Read([in] short nTable, [in] short nRow, [out, size_is(80)] LPWSTR lpszData);
		HRESULT Write([in] short nTable, [in] short nRow, [in] LPCWSTR lpszData);

		// Interface for database management
		HRESULT Create([out] REFSHORT nTable, [in] LPCWSTR lpszName);
		HRESULT Delete([in] short nTable);

		// Interfase para obtenber informacion sobre la base de datos
		HRESULT GetNumTables([out] REFSHORT nNumTables);
		HRESULT GetTableName([in] short nTable, [out, size_is(80)] LPWSTR lpszName);
		HRESULT GetNumRows([in] short nTable, [out] REFSHORT nRows);

}

[object, uuid(30DF3433-0266-11cf-BAA6-00AA003E0EED), pointer_default(unique)]
interface IDBAccess : IUnknown {
	  	// Interface for data access
		HRESULT Read([in] short nTable, [in] short nRow, [out, size_is(80)] LPWSTR lpszData);
		HRESULT Write([in] short nTable, [in] short nRow, [in] LPCWSTR lpszData);
}

[object, uuid(30DF3434-0266-11cf-BAA6-00AA003E0EED), pointer_default(unique)]
interface IDBManage : IUnknown {
	// Interface for database management
		HRESULT Create([out] REFSHORT nTable, [in] LPCWSTR lpszName);
		HRESULT Delete([in] short nTable);
}

[object, uuid(30DF3435-0266-11cf-BAA6-00AA003E0EED), pointer_default(unique)]
interface IDBInfo : IUnknown {
	// Interfase para obtenber informacion sobre la base de datos
		HRESULT GetNumTables([out] REFSHORT nNumTables);
		HRESULT GetTableName([in] short nTable, [out, size_is(80)] LPWSTR lpszName);
		HRESULT GetNumRows([in] short nTable, [out] REFSHORT nRows);
}

#endif
