# KallistiOS ##version##
#
# modules/drivers Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.2 2003/07/15 07:55:01 bardtx Exp $

all:
	$(KOS_MAKE) -C $(KOS_ARCH)

clean:
	$(KOS_MAKE) -C $(KOS_ARCH) clean

copy:
	$(KOS_MAKE) -C $(KOS_ARCH) copy
