	[
		uuid([!SnapInGUID]),
		helpstring("[!TypeName]")
	]
	coclass [!CoClassName]
	{
		[default] interface IUnknown;
	}
[!if=(ISnapinAbout, "TRUE")]
	[
		uuid([!SnapInAboutGUID]),
		helpstring("[!TypeName] About")
	]
	coclass [!CoClassName]About
	{
		[default] interface IUnknown;
	}
[!endif]
