/*************************************************************************
	Oracle 7 Database - Table Creation Script
	Tablespace - USER_DATA
	
	The following script creates the Oracle tables and views required
	for the sample Oracle program.
*************************************************************************/

/*************************************************************************
	LOG ON USING THE DEPT_ADMIN ACCOUNT	
*************************************************************************/
CONNECT DEPT_ADMIN/DEPT_ADMIN@WILBUR

/*************************************************************************
	CREATE DEPT AND CLASS TABLES
*************************************************************************/
DROP TABLE DEPT_ADMIN.DEPT CASCADE CONSTRAINTS
/

CREATE TABLE DEPT_ADMIN.DEPT
(DEPT            VARCHAR2(4) NOT NULL,
 DNAME           VARCHAR2(30) NOT NULL,
 CONSTRAINT DEPT_DEPT_PK PRIMARY KEY (DEPT)
        USING INDEX TABLESPACE USER_DATA
        PCTFREE 0 STORAGE (
                INITIAL 10K NEXT 10K 
                MINEXTENTS 1 MAXEXTENTS UNLIMITED),
CONSTRAINT DEPT_DNAME_UNIQUE UNIQUE (DNAME)
        USING INDEX TABLESPACE USER_DATA
        PCTFREE 0 STORAGE (
                INITIAL 10K NEXT 10K 
                MINEXTENTS 1 MAXEXTENTS UNLIMITED)
)
 PCTFREE 10
 PCTUSED 40
 TABLESPACE USER_DATA
 STORAGE (
        INITIAL 10K NEXT 10K 
        MINEXTENTS 1 MAXEXTENTS UNLIMITED
        FREELISTS 1)
/

DROP TABLE DEPT_ADMIN.CLASS CASCADE CONSTRAINTS
/
CREATE TABLE DEPT_ADMIN.CLASS
(CCODE           VARCHAR2(4) NOT NULL,
 CNAME           VARCHAR2(30) NOT NULL,
 DEPT            VARCHAR2(4) NOT NULL,
 ROOM            VARCHAR2(6) NULL,
 PREREQ          VARCHAR2(4) NULL,
 CONSTRAINT CLASS_CLASS_PK PRIMARY KEY (CCODE)
        USING INDEX TABLESPACE USER_DATA
        PCTFREE 0 STORAGE (
                INITIAL 10K NEXT 10K 
                MINEXTENTS 1 MAXEXTENTS UNLIMITED),
 CONSTRAINT CLASS_CNAME_UNIQUE UNIQUE (CNAME)
        USING INDEX TABLESPACE USER_DATA
        PCTFREE 0 STORAGE (
                INITIAL 10K NEXT 10K 
                MINEXTENTS 1 MAXEXTENTS UNLIMITED),
 CONSTRAINT CLASS_DEPT_FK FOREIGN KEY (DEPT) REFERENCES DEPT_ADMIN.DEPT (DEPT)
)
 PCTFREE 10
 PCTUSED 40
 TABLESPACE USER_DATA
 STORAGE (
        INITIAL 10K NEXT 10K 
        MINEXTENTS 1 MAXEXTENTS UNLIMITED
        FREELISTS 1)
/

CREATE INDEX DEPT_ADMIN.CLASS_DEPT_IDX ON DEPT_ADMIN.CLASS (DEPT)
TABLESPACE USER_DATA
PCTFREE 0
STORAGE (
	INITIAL 10K NEXT 10K 
	MINEXTENTS 1 MAXEXTENTS UNLIMITED)
/

GRANT REFERENCES ON DEPT_ADMIN.DEPT TO STUDENT_ADMIN
/

GRANT REFERENCES ON DEPT_ADMIN.CLASS TO STUDENT_ADMIN
/

/*************************************************************************
	ROLES ARE NOT ALLOWED GRANT OPTION, STUDENT_ADMIN NEEDS IT
*************************************************************************/
GRANT SELECT ON DEPT_ADMIN.DEPT TO STUDENT_ADMIN WITH GRANT OPTION
/

GRANT SELECT ON DEPT_ADMIN.CLASS TO STUDENT_ADMIN WITH GRANT OPTION
/

GRANT SELECT ON DEPT_ADMIN.DEPT TO USER_LOGON, DATA_ADMIN
/

GRANT SELECT ON DEPT_ADMIN.CLASS TO USER_LOGON, DATA_ADMIN
/

DROP PUBLIC SYNONYM DEPT
/

CREATE PUBLIC SYNONYM DEPT FOR DEPT_ADMIN.DEPT
/

DROP PUBLIC SYNONYM CLASS
/

CREATE PUBLIC SYNONYM CLASS FOR DEPT_ADMIN.CLASS
/

/*************************************************************************
	LOG ON USING THE STUDENT_ADMIN ACCOUNT
*************************************************************************/
CONNECT STUDENT_ADMIN/STUDENT_ADMIN@WILBUR

/*************************************************************************
	CREATE STUDENT AND GRADE TABLES, STUDENT_GPA VIEW
*************************************************************************/
DROP TABLE STUDENT_ADMIN.STUDENT CASCADE CONSTRAINTS
/

CREATE TABLE STUDENT_ADMIN.STUDENT
(SSN             CHAR(9) NOT NULL,
 FNAME           VARCHAR2(12) NULL,
 LNAME           VARCHAR2(20) NOT NULL,
 GENDER          CHAR(1) NOT NULL CONSTRAINT STUDENT_GENDER_CK CHECK (GENDER IN ('M', 'F')),
 MAJOR           VARCHAR2(4) DEFAULT 'Undc' NOT NULL,
 BIRTH_DATE      DATE NULL,
 TUITION_PAID    NUMBER(12,2) NULL,
 TUITION_TOTAL   NUMBER(12,2) NULL,
 START_DATE      DATE NULL,
 GRAD_DATE       DATE NULL,
 LOAN_AMOUNT     NUMBER(12,2) NULL,
 DEGREE_PROGRAM  CHAR(1) DEFAULT 'U' NOT NULL
                        CONSTRAINT STUDENT_DEGREE_CK CHECK (DEGREE_PROGRAM IN ('U','M','P','D')),
 CONSTRAINT STUDENT_SSN_PK PRIMARY KEY (SSN)
        USING INDEX TABLESPACE USER_DATA
        PCTFREE 0 STORAGE (
                INITIAL 10K NEXT 10K 
                MINEXTENTS 1 MAXEXTENTS UNLIMITED),
 CONSTRAINT STUDENT_MAJOR_FK FOREIGN KEY (MAJOR) REFERENCES DEPT_ADMIN.DEPT (DEPT)
)
 PCTFREE 10
 PCTUSED 40
 TABLESPACE USER_DATA
 STORAGE (
        INITIAL 10K NEXT 10K 
        MINEXTENTS 1 MAXEXTENTS UNLIMITED
        FREELISTS 1)
/

CREATE INDEX STUDENT_ADMIN.STUDENT_MAJOR_IDX ON STUDENT_ADMIN.STUDENT (MAJOR)
TABLESPACE USER_DATA
PCTFREE 0
STORAGE (
	INITIAL 10K NEXT 10K 
	MINEXTENTS 1 MAXEXTENTS UNLIMITED)
/

DROP TABLE STUDENT_ADMIN.GRADE CASCADE CONSTRAINTS
/

CREATE TABLE STUDENT_ADMIN.GRADE
(SSN             CHAR(9) NOT NULL,
 CCODE           VARCHAR2(4) NOT NULL,
 GRADE           VARCHAR2(2) NULL,
 CONSTRAINT GRADE_SSN_CCODE_PK PRIMARY KEY (SSN, CCODE)
        USING INDEX TABLESPACE USER_DATA
        PCTFREE 0 STORAGE (
                INITIAL 10K NEXT 10K 
                MINEXTENTS 1 MAXEXTENTS UNLIMITED),
 CONSTRAINT GRADE_SSN_FK FOREIGN KEY (SSN) REFERENCES STUDENT_ADMIN.STUDENT (SSN),
 CONSTRAINT GRADE_CCODE_FK FOREIGN KEY (CCODE) REFERENCES DEPT_ADMIN.CLASS (CCODE)
)
 PCTFREE 10
 PCTUSED 40
 TABLESPACE USER_DATA
 STORAGE (
        INITIAL 10K NEXT 10K 
        MINEXTENTS 1 MAXEXTENTS UNLIMITED
        FREELISTS 1)
/

CREATE INDEX STUDENT_ADMIN.GRADE_CCODE_IDX ON STUDENT_ADMIN.GRADE (CCODE)
TABLESPACE USER_DATA
PCTFREE 0
STORAGE (
	INITIAL 10K NEXT 10K 
	MINEXTENTS 1 MAXEXTENTS UNLIMITED)
/

DROP VIEW STUDENT_GPA
/

CREATE VIEW STUDENT_ADMIN.STUDENT_GPA (SSN, GPA) AS
SELECT SSN,
	ROUND(AVG(DECODE(grade
		,'A', 4
		,'A+', 4.3
		,'A-', 3.7
		,'B', 3
		,'B+', 3.3
		,'B-', 2.7
		,'C', 2
		,'C+', 2.3
		,'C-', 1.7
		,'D', 1
		,'D+', 1.3
		,'D-', 0.7
		,0)),2)
FROM STUDENT_ADMIN.GRADE
GROUP BY SSN
/

GRANT SELECT ON STUDENT_ADMIN.STUDENT TO USER_LOGON
/

GRANT SELECT, INSERT, UPDATE, DELETE ON STUDENT_ADMIN.STUDENT TO DATA_ADMIN
/

GRANT SELECT ON STUDENT_ADMIN.GRADE TO USER_LOGON
/

GRANT SELECT, INSERT, UPDATE, DELETE ON STUDENT_ADMIN.GRADE TO DATA_ADMIN
/

GRANT SELECT ON STUDENT_ADMIN.STUDENT_GPA TO USER_LOGON, DATA_ADMIN
/

DROP PUBLIC SYNONYM STUDENT
/

CREATE PUBLIC SYNONYM STUDENT FOR STUDENT_ADMIN.STUDENT
/

DROP PUBLIC SYNONYM GRADE
/

CREATE PUBLIC SYNONYM GRADE FOR STUDENT_ADMIN.GRADE
/

DROP PUBLIC SYNONYM STUDENT_GPA
/

CREATE PUBLIC SYNONYM STUDENT_GPA FOR STUDENT_ADMIN.STUDENT_GPA
/