/*************************************************************************
	SQL Server Database - Table Creation Script
	Database - USER_DB
	
	The following script creates the SQL Server tables and views required
	for the sample SQL Server program.
*************************************************************************/

/*************************************************************************
	YOU MUST BE LOGGED ON AS 'SA' TO RUN THIS SCRIPT
*************************************************************************/

/*************************************************************************
	USING USER_DB DATABASE
*************************************************************************/
USE USER_DB
GO

/*************************************************************************
	DROP TABLES (IF THEY EXIST)	
*************************************************************************/

DROP TABLE STUDENT_ADMIN.GRADE
GO

DROP TABLE STUDENT_ADMIN.STUDENT
GO

DROP TABLE DEPT_ADMIN.CLASS
GO

DROP TABLE DEPT_ADMIN.DEPT
GO

/*************************************************************************
	CREATE DEPT AND CLASS TABLES
*************************************************************************/

CREATE TABLE DEPT_ADMIN.DEPT
(DEPT            VARCHAR(4) NOT NULL,
 DNAME           VARCHAR(30) NOT NULL,
 CONSTRAINT DEPT_DEPT_PK PRIMARY KEY CLUSTERED (DEPT),
 CONSTRAINT DEPT_DNAME_UNIQUE UNIQUE NONCLUSTERED (DNAME)
)
GO

CREATE TABLE DEPT_ADMIN.CLASS
(CCODE           VARCHAR(4) NOT NULL,
 CNAME           VARCHAR(30) NOT NULL,
 DEPT            VARCHAR(4) NOT NULL,
 ROOM            VARCHAR(6) NULL,
 PREREQ          VARCHAR(4) NULL,
 CONSTRAINT CLASS_CLASS_PK PRIMARY KEY CLUSTERED (CCODE),
 CONSTRAINT CLASS_CNAME_UNIQUE UNIQUE NONCLUSTERED (CNAME),
 CONSTRAINT CLASS_DEPT_FK FOREIGN KEY (DEPT) REFERENCES DEPT_ADMIN.DEPT (DEPT)
)
GO

CREATE NONCLUSTERED INDEX CLASS_DEPT_IDX ON DEPT_ADMIN.CLASS (DEPT)
GO

GRANT REFERENCES ON DEPT_ADMIN.DEPT TO DATA_ADMIN
GO

GRANT REFERENCES ON DEPT_ADMIN.CLASS TO DATA_ADMIN
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON DEPT_ADMIN.DEPT TO DATA_ADMIN
GO

GRANT SELECT ON DEPT_ADMIN.DEPT TO USER_LOGON
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON DEPT_ADMIN.CLASS TO DATA_ADMIN
GO

GRANT SELECT ON DEPT_ADMIN.CLASS TO USER_LOGON
GO

/*************************************************************************
	CREATE STUDENT AND GRADE TABLES, STUDENT_GPA VIEW
*************************************************************************/

CREATE TABLE STUDENT_ADMIN.STUDENT
(SSN             CHAR(9) NOT NULL,
 FNAME           VARCHAR(12) NULL,
 LNAME           VARCHAR(20) NOT NULL,
 GENDER          CHAR(1) NOT NULL CONSTRAINT STUDENT_GENDER_CK
			CHECK (GENDER IN ('M', 'F')),
 MAJOR           VARCHAR(4) NOT NULL CONSTRAINT STUDENT_MAJOR_DEF
			DEFAULT 'Undc',
 BIRTH_DATE      DATETIME NULL,
 TUITION_PAID    NUMERIC(12,2) NULL,
 TUITION_TOTAL   NUMERIC(12,2) NULL,
 START_DATE      DATETIME NULL,
 GRAD_DATE       DATETIME NULL,
 LOAN_AMOUNT     NUMERIC(12,2) NULL,
 DEGREE_PROGRAM  CHAR(1) NOT NULL CONSTRAINT STUDENT_DEGREE_DEF DEFAULT 'U'
 CONSTRAINT STUDENT_DEGREE_CK CHECK (DEGREE_PROGRAM IN ('U','M','P','D')),
 CONSTRAINT STUDENT_SSN_PK PRIMARY KEY CLUSTERED (SSN),
 CONSTRAINT STUDENT_MAJOR_FK FOREIGN KEY (MAJOR)
			REFERENCES DEPT_ADMIN.DEPT (DEPT)
)
GO

CREATE NONCLUSTERED INDEX STUDENT_MAJOR_IDX ON STUDENT_ADMIN.STUDENT (MAJOR)
GO

CREATE TABLE STUDENT_ADMIN.GRADE
(SSN             CHAR(9) NOT NULL,
 CCODE           VARCHAR(4) NOT NULL,
 GRADE           VARCHAR(2) NULL,
 CONSTRAINT GRADE_SSN_CCODE_PK PRIMARY KEY CLUSTERED (SSN, CCODE),
 CONSTRAINT GRADE_SSN_FK FOREIGN KEY (SSN)
			REFERENCES STUDENT_ADMIN.STUDENT (SSN),
 CONSTRAINT GRADE_CCODE_FK FOREIGN KEY (CCODE)
			REFERENCES DEPT_ADMIN.CLASS (CCODE)
)
GO

CREATE NONCLUSTERED INDEX GRADE_CCODE_IDX ON STUDENT_ADMIN.GRADE (CCODE)
GO

DROP VIEW STUDENT_ADMIN.STUDENT_GPA
GO

CREATE VIEW STUDENT_ADMIN.STUDENT_GPA (SSN, GPA) AS
SELECT SSN,
	ROUND(AVG(CASE grade
		WHEN 'A' THEN 4
		WHEN 'A+' THEN 4.3
		WHEN 'A-' THEN 3.7
		WHEN 'B' THEN 3
		WHEN 'B+' THEN 3.3
		WHEN 'B-' THEN 2.7
		WHEN 'C' THEN 2
		WHEN 'C+' THEN 2.3
		WHEN 'C-' THEN 1.7
		WHEN 'D' THEN 1
		WHEN 'D+' THEN 1.3
		WHEN 'D-' THEN 0.7
		ELSE 0
		END),2)
FROM STUDENT_ADMIN.GRADE
GROUP BY SSN
GO

GRANT SELECT ON STUDENT_ADMIN.STUDENT TO USER_LOGON
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON STUDENT_ADMIN.STUDENT TO DATA_ADMIN
GO

GRANT SELECT ON STUDENT_ADMIN.GRADE TO USER_LOGON
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON STUDENT_ADMIN.GRADE TO DATA_ADMIN
GO

GRANT SELECT ON STUDENT_ADMIN.STUDENT_GPA TO USER_LOGON, DATA_ADMIN
GO
