// FinSrvr.idl : IDL source for FinSrvr.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (FinSrvr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#include "PerfCtrs.idl"

	[
		object,
		uuid(0166BE92-87E2-11D1-8DB5-204C4F4F5020),
		dual,
		helpstring("IFinSessn Interface"),
		pointer_default(unique)
	]
	interface IFinSessn : IDispatch
	{
	};
	[
		object,
		uuid(0166BE94-87E2-11D1-8DB5-204C4F4F5020),
		dual,
		helpstring("ICFinCntrs Interface"),
		pointer_default(unique)
	]
	interface ICFinCntrs : IDispatch
	{
	};
[
	uuid(0166BE85-87E2-11D1-8DB5-204C4F4F5020),
	version(1.0),
	helpstring("FinSrvr 1.0 Type Library")
]
library FINSRVRLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(0166BE93-87E2-11D1-8DB5-204C4F4F5020),
		helpstring("FinSessn Class")
	]
	coclass FinSessn
	{
		[default] interface IFinSessn;
	};
	[
		uuid(B0A6AA96-76F5-11D1-8D92-204C4F4F5020),
		helpstring("CFinCntrs Class")
	]
	coclass CFinCntrs
	{
		[default] interface ICFinCntrs;
	};

	[
		uuid(7E3EC2E1-87F0-11d1-8DB5-204C4F4F5020),
		helpstring("temp to include IPerfmonCounter in typelib")
	]
	coclass CTemp1
	{
		[default] interface IPerfmonObject;
	};

	[
		uuid(EE91F7C2-87EF-11d1-8DB5-204C4F4F5020),
		helpstring("temp to include IPerfmonCounter in typelib")
	]
	coclass CTemp2
	{
		[default] interface IPerfmonCounter;
	};
};
