// RegPCtrs.idl : IDL source for RegPCtrs.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (RegPCtrs.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(0166BEA2-87E2-11D1-8DB5-204C4F4F5020),
		dual,
		helpstring("IRegisterPerfmonObject Interface"),
		pointer_default(unique)
	]
	interface IRegisterPerfmonObject : IDispatch
	{
		[helpstring("Adds the performance counters to the registry")]
		[id(1)]
		HRESULT Register([in]BSTR appName, [in]BSTR collectionGUID);

		[helpstring("Removes the performance counters to the registry")]
		[id(2)]
		HRESULT Unregister([in]BSTR appName);
	};
[
	uuid(0166BE95-87E2-11D1-8DB5-204C4F4F5020),
	version(1.0),
	helpstring("RegPCtrs 1.0 Type Library")
]
library REGPCTRSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(8F2BBC80-1257-11D1-9F91-400004491341),
		helpstring("RegisterPerfmonObject Class")
	]
	coclass RegisterPerfmonObject
	{
		[default] interface IRegisterPerfmonObject;
	};
};
