# KallistiOS ##version##
#
# thread/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.4 2003/02/14 08:25:07 bardtx Exp $

OBJS =  sem.o cond.o mutex.o genwait.o
OBJS += thread.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



