# KallistiOS ##version##
#
# kernel/libc/pthreads/Makefile
# Copyright (C)2004 Dan Potter
#

# Minimalist pthreads to KOS mapping. Programs that really intensively
# use pthreads may cause problems but basic stuff should work.

OBJS = pthread_mutex.o pthread_cond.o pthread_thd_attr.o pthread_thd.o \
	pthread_tls.o

include $(KOS_BASE)/Makefile.prefab
