#------------------------------------------------------------------------------
# FourPasses.mak
#------------------------------------------------------------------------------

PROJECT =	FourPasses

PROJECT_SRC	= \
		sbinit.c\
		Data.c\
		KMBump.c\
		KMLight.c\
		KMMatrix.c\
		KMMisc.c\
		KMPrint3D.c\
		KMTexture.c\
		KMTimer.c\
		KMTransform.c\
		VQCalc.c\
		KMShell_8Passes.c\
		FourPasses.c\

OPTIMIZE =	0

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
