#!/bin/sh

# This actually does require bash...


# Just supplement the standard C flags and call down.
export KOS_CC="${KOS_CCPLUS}"
export KOS_CFLAGS="${KOS_CFLAGS} ${KOS_CPPFLAGS}"
export KOS_LIBS="-lstdc++ ${KOS_LIBS}"

exec ${0%%kos-c++}kos-cc "$@"
