VBDSS1.FRM
VBDSS.BAS
VBODBC.BAS
VBEXCEL.BAS
VBSEC.BAS
C:\WINDOWS\SYSTEM\GRID.VBX
VBDSS2.FRM
VBDSS3.FRM
VBODBC1.FRM
VBODBC2.FRM
ProjWinSize=56,410,236,399
ProjWinShow=2
IconForm="frmDssSnapshotMgr"
Title="VB Decision Support Template"
ExeName="VBDSS.EXE"
