#------------------------------------------------------------------------------
# k2seal.mak
#------------------------------------------------------------------------------

PROJECT =	k2seal

PROJECT_SRC	= \
		dispstr.c\
		ground.c\
		kmseal.c\
		main.c\
		sbinit.c\
		sea.c\
		seal.c\
		sky.c\
		texchar.c\

OPTIMIZE =	0

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
