/*++

  COPYRIGHT        (C) NEC        Corporation 1997 - 1999

  All rights reserved by NEC Corporation. This program must be
  used solely for the purpose for which it was furnished by NEC
  Corporation. No part of this program may be reproduced or
  disclosed to others, in any form, without the prior written
  permission of NEC Corporation.
  Use of copyright notice does not evidence publication of this
  program.

  Author	:  		T.Muto(NEC Software Ltd.,)
  Module Name:		VLTex.h

--*/
/*************************************************/
/* Videologic サンプルプログラム用テクスチャ定義 */
/*************************************************/
extern unsigned char *ble_back;
extern unsigned char *ble_gold;
extern unsigned char *ble_opaq;
extern unsigned char *ble_trans;
extern unsigned char *cyb_cyberk;
extern unsigned char *cyb_cyground;
extern unsigned char *cyb_cysky;
extern unsigned char *fli_bat;
extern unsigned char *fli_fire;
extern unsigned char *fli_ground;
extern unsigned char *fli_shadow;
extern unsigned char *fli_thorm;
extern unsigned char *gas_gsface;
extern unsigned char *gas_gsfire;
extern unsigned char *gas_gsfirer;
extern unsigned char *gas_gsglass;
extern unsigned char *gas_gstorso;
extern unsigned char *log_pvr;
extern unsigned char *log_reflect;
extern unsigned char *log_title;
extern unsigned char *mar_bark;
extern unsigned char *mar_marble;
extern unsigned char *mar_marble2;
extern unsigned char *mas_backrfl1;
extern unsigned char *mas_backrfl2;
extern unsigned char *mas_backrfl3;
extern unsigned char *mas_mfront01;
extern unsigned char *mas_mfront02;
extern unsigned char *mas_mfront03;
extern unsigned char *mas_mground;
extern unsigned char *mas_mreflect;
extern unsigned char *nau_imagine;
extern unsigned char *nau_reflect;
extern unsigned char *nef_pvrlogo;
extern unsigned char *nef_rivets;
extern unsigned char *sea_ground;
extern unsigned char *sea_sea;
extern unsigned char *sea_seal;
extern unsigned char *sea_sky;
extern unsigned char *spa_space;
extern unsigned char *sta_stground;
extern unsigned char *sta_stlight;
extern unsigned char *sta_stpvr;
extern unsigned char *sta_stpvr2;
extern unsigned char *str_backgrnd;
extern unsigned char *str_strip;
extern unsigned char *str_strip1;
extern unsigned char *toy_back;
extern unsigned char *toy_opaq;
extern unsigned char *tr1_bark;
extern unsigned char *tr1_forest;
extern unsigned char *tr1_leaf;
extern unsigned char *tr2_leaf;
extern unsigned char *tr2_snow;
extern unsigned char *tr2_tree;
extern unsigned char *tr2_ttree;

/*-- End of Flie -----------------------------------------------------------------*/
