# KallistiOS ##version##
#
# arch/dreamcast/navi/Makefile
# (c)2002 Dan Potter
#
# $Id: Makefile,v 1.1 2002/05/05 22:16:49 bardtx Exp $

# IDE
OBJS += navi_ide.o

# Flash BIOS
OBJS += navi_flash.o

# SUBDIRS = fs
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab



