# KallistiOS ##version##
#
# misc/Makefile
# (c)2000-2002 Dan Potter
#   
# $Id: Makefile,v 1.3 2002/09/05 07:33:25 bardtx Exp $

OBJS = bspline.o img.o pcx_small.o 
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab


