##-----------------------------------------------------------------------------
##
##	FILE:		actransfer.mak
##
##	DESC:		Makefile for actransfer sample
##
##	HISTORY:	2000.01.xx	Reworked samples/boilerplates for R10 release.
##
##-----------------------------------------------------------------------------

PROJECT			= actransfer

PROJECT_SRC		=\
				sbinit.c\
				main.c\
				bpacsetup.c\
				bpprintf.c

SYSTEM_LIBS		=\
				audio64

OPTIMIZE		= 1

#COMPILER		= SHC
GFXLIB			= NINJA
OUTPUT			= ELF

DEBUG			= TRUE
LIST			= FALSE

include $(KATANA_ROOT)\sample\dc.inc
