# KallistiOS ##version##
#
# examples/dreamcast/sound/cdda/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/07/17 15:14:16 axlen Exp $

all:
	$(KOS_MAKE) -C basic_cdda

clean:
	$(KOS_MAKE) -C basic_cdda clean
		
dist:
	$(KOS_MAKE) -C basic_cdda dist


