#------------------------------------------------------------------------------
#TileClip.mak
#------------------------------------------------------------------------------

PROJECT =	TileClip

PROJECT_SRC	= \
		main.c\
		model.c\
		sbinit.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	BIN

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
