#------------------------------------------------------------------------------
#k2nautil.mak
#------------------------------------------------------------------------------

PROJECT =	k2nautil

PROJECT_SRC	= \
		DISPSTR.C\
		IMAGINE.C\
		KMNAUTIL.C\
		KMNTOOL.C\
		MAIN.C\
		REFLECT.C\
		sbinit.c\
		TEXCHAR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
