# KallistiOS ##version##
#
# examples/dreamcast/basic/fpu/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/05/18 07:08:35 bardtx Exp $

all:
	$(KOS_MAKE) -C exc

clean:
	$(KOS_MAKE) -C exc clean
		
dist:
	$(KOS_MAKE) -C exc dist


