/* This header file machine-generated by mktyplib.exe */
/* Interface to type library: SphereSquareLibrary */

#ifndef _SphereSquareLibrary_H_
#define _SphereSquareLibrary_H_

DEFINE_GUID(LIBID_SphereSquareLibrary,0x00021169,0x0000,0x0000,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46);

DEFINE_GUID(IID_ISphereSquare,0x00021168,0x0000,0x0000,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46);

/* Definition of interface: ISphereSquare */
DECLARE_INTERFACE_(ISphereSquare, IUnknown)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;
#endif

    /* ISphereSquare methods */
    STDMETHOD_(double, get_Radius)(THIS) PURE;
    STDMETHOD_(void, put_Radius)(THIS_ double Radius) PURE;
    STDMETHOD_(double, get_Theta)(THIS) PURE;
    STDMETHOD_(void, put_Theta)(THIS_ double Theta) PURE;
    STDMETHOD_(double, get_Declination)(THIS) PURE;
    STDMETHOD_(void, put_Declination)(THIS_ double Declination) PURE;
    STDMETHOD_(long, get_BackColor)(THIS) PURE;
    STDMETHOD_(void, put_BackColor)(THIS_ long BackColor) PURE;
    STDMETHOD_(long, get_LineColorPositive)(THIS) PURE;
    STDMETHOD_(void, put_LineColorPositive)(THIS_ long LineColorPositive) PURE;
    STDMETHOD_(long, get_LineColorNegative)(THIS) PURE;
    STDMETHOD_(void, put_LineColorNegative)(THIS_ long LineColorNegative) PURE;
    STDMETHOD_(void, Draw)(THIS) PURE;
    STDMETHOD_(void, SetCenterPoint)(THIS_ int CenterX, int CenterY) PURE;
    STDMETHOD_(void, ShowWindow)(THIS_ int ShowCommand) PURE;
    STDMETHOD_(void, SetWindowPosition)(THIS_ int Left, int Top) PURE;
    STDMETHOD_(void, SetWindowSize)(THIS_ int Width, int Height) PURE;
};

DEFINE_GUID(DIID_DISphereSquare,0x0002116A,0x0000,0x0000,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46);

/* Definition of dispatch interface: DISphereSquare */
DECLARE_INTERFACE_(DISphereSquare, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

/* Capable of dispatching all the methods of interface ISphereSquare */
};

DEFINE_GUID(CLSID_SphereSquare,0x00021167,0x0000,0x0000,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46);

class SphereSquare;

#endif
