// hellojtx.idl : IDL source for hellojtx.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (hellojtx.tlb).


#include <MtxAttr.h>
#include <JavaAttr.h>


[
	uuid(CBD73841-C640-11d0-BD14-0080C7C1FC93),
	version(1.0),
	helpstring("Simple Microsoft Transaction Server sample, written in Java")
]
library HELLOJTXLib
{

	importlib("stdole2.tlb");


	[
		object,
		uuid(CBD73842-C640-11d0-BD14-0080C7C1FC93),
		dual,
		helpstring("IHellojtx Interface"),
		pointer_default(unique)
	]
	interface IHellojtx : IDispatch
	{
		import "oaidl.idl";
		HRESULT SayHello([out] BSTR* pbstrResult, [out, retval] long* plRetVal);
	};



	[
		uuid(CBD73843-C640-11d0-BD14-0080C7C1FC93),
		helpstring("Hello Class"),
		JAVACLASS("Hellojtx.HelloObj"),
		PROGID("Hellojtx.Hello"),
		TRANSACTION_REQUIRED
	]
	coclass CHellojtx
	{
		[default] interface IHellojtx;
	};
};
