# KallistiOS ##version##
#
# arch/dreamcast Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/06/19 04:20:59 bardtx Exp $
	
SUBDIRS=fs hardware math sound util

include $(KOS_BASE)/Makefile.rules

all: subdirs
clean: clean_subdirs
