#------------------------------------------------------------------------------
#lcd0.mak
#------------------------------------------------------------------------------

PROJECT =	lcd0

PROJECT_SRC	= \
		cgdata.c\
		njloop.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
