#
# Libdream Examples
# (c)2000-2001 Dan Potter
#

TARGET = $(BIN).elf

all: $(TARGET)

include $(KOS_BASE)/Makefile.rules

clean:
	rm -f $(TARGET) $(OBJS) $(EXTRA_CLEAN)

rm-elf:
	rm -f $(TARGET)

$(TARGET): $(OBJS)
	$(KOS_CC) $(KOS_CFLAGS) $(KOS_LDFLAGS) -o $(TARGET) $(KOS_START) \
		$(OBJS) $(DATAOBJS) $(OBJEXTRA) -L$(KOS_BASE)/lib \
		$(EXTRA_LIBS) -lkallisti -lgcc

dist:
	rm -f $(OBJS) $(EXTRA_CLEAN)
	$(KOS_CC_BASE)/bin/sh-elf-strip $(TARGET)

