#------------------------------------------------------------------------------
# DPBrowser.mak
#------------------------------------------------------------------------------

PROJECT	= DPBrowser

PROJECT_SRC	= \
		njloop.c\
		test.c\
		sbinit.c\

SYSTEM_LIBS	= \
		sg_dpldr\
		nt_utl\
		nindows\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
