# KallistiOS ##version##
#
# loadable Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.3 2003/07/24 03:33:28 bardtx Exp $

DIRS = libcrt libexports libkos modules programs

include Makefile.subdirs

#copy:
#	for i in `find . -iname "*.elf" | grep -v '/dbg-'`; do cp $$i ../kernel/romdisk; done
