# KallistiOS ##version##
#
# loadable/Makefile.subdirs
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile.subdirs,v 1.1 2003/07/31 00:55:41 bardtx Exp $

# Expects "DIRS" to be set already

all:
	for i in $(DIRS); do $(KOS_MAKE) -C $$i; done

clean:
	for i in $(DIRS); do $(KOS_MAKE) -C $$i clean; done

copy:
	for i in $(DIRS); do $(KOS_MAKE) -C $$i copy; done
