#------------------------------------------------------------------------------
# CheapTst.mak
#------------------------------------------------------------------------------

PROJECT =	CheapTst

PROJECT_SRC	= \
		cheaptst.c\
		sbinit.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
