# KallistiOS ##version##
#
# examples/ps2/basic/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/10/27 23:41:13 bardtx Exp $

all:
	$(KOS_MAKE) -C hello

clean:
	$(KOS_MAKE) -C hello clean
		
dist:
	$(KOS_MAKE) -C hello dist

