# KallistiOS ##version##
#
# examples/dreamcast/video/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/07/10 16:51:42 bardtx Exp $

all:
	$(KOS_MAKE) -C bfont

clean:
	$(KOS_MAKE) -C bfont clean
		
dist:
	$(KOS_MAKE) -C bfont dist


