USE_ODBC=1
Proj = CrsrDemo

!include <BkOffice.Mak>

All: $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(@R).Obj $(@D)\Child.Obj $(@D)\Dialogs.Obj $(@D)\Frame.Obj \
                       $(@D)\Headers.Obj  $(@R).Res
