#------------------------------------------------------------------------------
#k2staind.mak
#------------------------------------------------------------------------------

PROJECT =	k2staind

PROJECT_SRC	= \
		DISPSTR.C\
		KMSTAIND.C\
		MAIN.C\
		sbinit.c\
		STGROUND.C\
		STLIGHT.C\
		STPVR.C\
		STPVR2.C\
		TEXCHAR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
