#------------------------------------------------------------------------------
#vib00.mak
#------------------------------------------------------------------------------

PROJECT =	vib00

PROJECT_SRC	= \
		main.c\
		sbinit.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
