# KallistiOS ##version##
#
# examples/dreamcast/parallax/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/09/10 04:40:10 bardtx Exp $

all:
	$(KOS_MAKE) -C font
	$(KOS_MAKE) -C bubbles

clean:
	$(KOS_MAKE) -C font clean
	$(KOS_MAKE) -C bubbles clean
		
dist:
	$(KOS_MAKE) -C font dist
	$(KOS_MAKE) -C bubbles dist


