/*****************************************************************************\
*                                                                             *
* DataPath.h    Obsolete DataPath header                                      *
*                                                                             *
*               Copyright 1995 - 1998 Microsoft Corp. All rights reserved.     *
*                                                                             *
\*****************************************************************************/

#ifndef __datapath_h__
#define __datapath_h__
#pragma message("WARNING: your code should #include ocidl.h instead of datapath.h")
#include <ocidl.h>
#endif
