//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright 1996 - 1998 Microsoft Corporation
//
//  File:       sipbase.h
//
//  Contents:   Generic SIP Provider Main Include File
//
//  History:    14-Feb-1997 pberkman   created
//
//--------------------------------------------------------------------------

#ifndef SIPBASE_H
#define SIPBASE_H

// all moved to mssip.h
#include <mssip.h>

#endif // SIPBASE_H
