//
//  Defines for server types
//
#define SRVTEXT        SRV_TDS_TEXT
#define SRVVARBINARY   SRV_TDS_VARBINARY
#define SRVINTN        SRV_TDS_INTN
#define SRVVARCHAR     SRV_TDS_VARCHAR
#define SRVLOGIN       SRV_TDS_LOGIN
#define SRVBINARY      SRV_TDS_BINARY
#define SRVIMAGE       SRV_TDS_IMAGE
#define SRVCHAR        SRV_TDS_CHAR
#define SRVINT1        SRV_TDS_INT1
#define SRVBIT         SRV_TDS_BIT
#define SRVINT2        SRV_TDS_INT2
#define SRVINT4        SRV_TDS_INT4
#define SRVMONEY       SRV_TDS_MONEY
#define SRVDATETIME    SRV_TDS_DATETIME
#define SRVFLT8        SRV_TDS_FLT8
#define SRVFLTN        SRV_TDS_FLTN
#define SRVMONEYN      SRV_TDS_MONEYN
#define SRVDATETIMN    SRV_TDS_DATETIMN
#define SRVOFFSET      SRV_TDS_OFFSET
#define SRVRETURNSTATUS SRV_TDS_RETURNSTATUS
#define SRVPROCID      SRV_TDS_PROCID
#define SRVCOLNAME     SRV_TDS_COLNAME
#define SRVCOLFMT      SRV_TDS_COLFMT
#define SRVTABNAME     SRV_TDS_TABNAME
#define SRVCOLINFO     SRV_TDS_COLINFO
#define SRVORDER       SRV_TDS_ORDER
#define SRVERROR       SRV_TDS_ERROR
#define SRVINFO        SRV_TDS_INFO
#define SRVRETURNVALUE SRV_TDS_RETURNVALUE
#define SRVCONTROL     SRV_TDS_CONTROL
#define SRVROW         SRV_TDS_ROW
#define SRVDONE        SRV_TDS_DONE
#define SRVDONEPROC    SRV_TDS_DONEPROC
#define SRVDONEINPROC  SRV_TDS_DONEINPROC

//
// These are version 4.2 additions
//
#define SRVFLT4        SRV_TDS_FLT4    
#define SRVMONEY4      SRV_TDS_MONEY4  
#define SRVDATETIM4    SRV_TDS_DATETIM4

#define SRVNULL        SRV_TDS_NULL    // Null parameter from server

//
// These are version 6.0 additions
//
#define SRVNUMERIC	SRV_TDS_NUMERIC
#define SRVNUMERICN	SRV_TDS_NUMERICN

#define SRVDECIMAL	SRV_TDS_DECIMAL
#define SRVDECIMALN	SRV_TDS_DECIMALN
