# Makefile to build the Sample CMC Client

# Key to CPU specific conditions, CPU == i386 || ALPHA || MIPS || PPC
!IF "$(CPU)" == ""
!IF "$(PROCESSOR_ARCHITECTURE)" == "MIPS" || "$(PROCESSOR_ARCHITECTURE)" == "ALPHA" || "$(PROCESSOR_ARCHITECTURE)" == "PPC"
CPU = $(PROCESSOR_ARCHITECTURE)
!ELSE
CPU = i386
!ENDIF
!ENDIF

!IFDEF MAPISAMP
HOME   = $(MAPISAMP)\cmc.cli^\
COMMON = $(MAPISAMP)\common^\
!ELSE
HOME   = 
COMMON = ..\common^\
!ENDIF

!include <$(COMMON)win16.mak>

!IFNDEF NODEBUG
cflags = $(cflags) -DDEBUG
!ENDIF

PROJ = CMCCLI

# Main target dependencies

all: $(PROJ).exe

# Extra libraries needed, not defined in win32.mak

extralibs = lzexpand.lib

# Object files we need tp build

OBJS = cmccli.obj 
COMMON_OBJS = pvalloc.obj

# Build the object files

{$(HOME)}.c.obj:
  set cl=-I$(COMMON) $(cdebug) $(cflags) $(cvars)
  $(cc) $**

pvalloc.obj: $(COMMON)pvalloc.c
  set cl=-I$(COMMON) $(cdebug) $(cflags) $(cvars)
  $(cc) $**

# Build the resources

$(PROJ).res: $(HOME)cmccli.rc $(HOME)cmccli.ico $(HOME)cmccli2.ico \
             $(HOME)read.bmp $(HOME)unread.bmp $(HOME)reada.bmp \
			 $(HOME)unreada.bmp
  set INCLUDE=$(INCLUDE);$(HOME);$(COMMON)
  $(rc) $(rcflags) $(rcvars) /fo $(PROJ).res $(HOME)CMCCLI.RC

# Link it together to make the executable image

$(PROJ).exe: $(OBJS) $(COMMON_OBJS) $(PROJ).res
  echo $(OBJS) $(COMMON_OBJS) > link.txt
  echo $(PROJ).exe >> link.txt
  echo $(PROJ).map >> link.txt
  echo $(extralibs) $(guilibs) >> link.txt
  echo $(HOME)cmccli16.def >> link.txt
  $(link) $(ldebug) $(lflags) @link.txt
  $(rc) -t $(PROJ).res $@
!IFDEF MAPISAMP
  -copy $@ $(MAPISAMP)\bin\$(PLATFORM)
!ENDIF

# Clean up the intermediate files

clean:
  -del *.obj
  -del *.res
  -del *.exe
  -del *.map
  -del link.txt
