# KallistiOS ##version##
#
# mm/Makefile
# (c)2000-2001 Dan Potter
#   
# $Id: Makefile,v 1.3 2002/02/23 07:00:57 bardtx Exp $

# Uncomment this line if you want normal operation
OBJS = malloc.o cplusplus.o

# Uncomment this if you want a debug malloc(). NOTE: This is not a magical
# holy grail debugging tool, it will probably screw up your code if you use
# much memory over time. See the source for details.
# OBJS = malloc_debug.o cplusplus.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab

