# KallistiOS ##version##
#
# utils/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.5 2002/12/12 20:35:48 gilm Exp $

all:
	$(KOS_MAKE) -C genromfs
	$(KOS_MAKE) -C wav2adpcm
	$(KOS_MAKE) -C vqenc
	$(KOS_MAKE) -C gba-crcfix

clean:
	$(KOS_MAKE) -C genromfs clean
	$(KOS_MAKE) -C wav2adpcm clean
	$(KOS_MAKE) -C vqenc clean
	$(KOS_MAKE) -C gba-crcfix clean
		

