//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VControl.rc
//
#define IDS_VCONTROL                    1
#define IDD_ABOUTBOX_VCONTROL           1
#define IDB_VCONTROL                    1
#define IDI_ABOUTDLL                    1
#define IDS_VCONTROL_PPG                2
#define IDS_NOTENOUGHMEMORY             3
#define IDS_OPTIONAL                    4
#define IDS_MANDATORY                   5
#define IDS_VCONTROL_PPG_CAPTION        100
#define IDD_PROPPAGE_VCONTROL           100
#define IDS_VERIFY_CONTAINER            101
#define IDS_VCONTROL_PPG_CAPTION2       102
#define IDS_IOleClientSiteSaveObject    105
#define IDS_IOleClientSiteGetMoniker    106
#define IDS_IOleClientSiteGetContainer  107
#define IDS_IOleClientSiteShowObject    108
#define IDS_IOleClientSiteOnShowWindow  109
#define IDS_IOleClientSiteRequestNewObjectLayout 110
#define IDS_IOleInPlaceSiteGetWindow    111
#define IDS_IOleInPlaceSiteContextSensitiveHelp 112
#define IDS_IOleInPlaceSiteCanInPlaceActivate 113
#define IDS_IOleInPlaceSiteOnInPlaceActivate 114
#define IDS_IOleInPlaceSiteOnUIActivate 115
#define IDS_IOleInPlaceSiteGetWindowContext 116
#define IDS_IOleInPlaceSiteScroll       117
#define IDS_IOleInPlaceSiteOnUIDeactivate 118
#define IDS_IOleInPlaceSiteOnInPlaceDeactivate 119
#define IDS_IOleInPlaceFrameContextSensitiveHelp 120
#define IDS_IOleInPlaceSiteDiscardUndoState 121
#define IDS_IOleInPlaceSiteDeactivateAndUndo 123
#define IDS_IOleInPlaceSiteOnPosRectChange 125
#define IDC_RESULTSFILE                 203
#define IDC_MANDATORYSUCCCESS           205
#define IDD_RESULTSDIALOG               205
#define IDC_MANDATORYFAILURES           206
#define IDC_OPTIONALTESTS               207
#define IDC_LIST_RESULT_TEXT            1002
#define IDS_CONTROL_PASSED              1010
#define IDS_CONTROL_FAILED              1011
#define IDC_CHK_MANDATORY               1026
#define IDC_CHK_OPTIONAL                1027
#define IDC_CHK_SUCCESS                 1028
#define IDC_CHK_FAIL                    1029
#define IDM_TESTMENU                    32768
#define IDS_IOleInPlaceFrameGetWindow   0xE300
#define IDS_IOleInPlaceFrameGetBorder   58113
#define IDS_IOleInPlaceFrameRequestBorderSpace 58114
#define IDS_IOleInPlaceFrameSetBorderSpace 58115
#define IDS_IOleInPlaceFrameSetActiveObject 58116
#define IDS_IOleInPlaceFrameInsertMenus 58117
#define IDS_IOleInPlaceFrameSetMenu     58118
#define IDS_IOleInPlaceFrameRemoveMenus 58119
#define IDS_IOleInPlaceFrameSetStatusText 58120
#define IDS_IOleInPlaceFrameEnableModeless 58121
#define IDS_IOleInPlaceFrameTranslateAccelerator 58122
#define IDS_IOleControlSiteOnControlInfoChanged 58123
#define IDS_IOleControlSiteLockInPlaceActive 58124
#define IDS_IOleControlSiteGetExtendedControl 58125
#define IDS_IOleControlSiteTransformCoords 58126
#define IDS_IOleControlSiteTranslateAccelerator 58127
#define IDS_IOleControlSiteOnFocus      58128
#define IDS_IOleControlSiteShowPropertyFrame 58129
#define IDS_IOleContainerEnumObjects    58130
#define IDS_IOleContainerLockContainer  58131
#define IDS_IDispatchAmbientsGetTypeInfoCount 58132
#define IDS_IDispatchAmbientsGetTypeInfo 58133
#define IDS_IDispatchAmbientsGetIDsOfNames 58134
#define IDS_IDispatchAmbientsInvokeLocaleID 58135
#define IDS_IDispatchAmbientsInvokeUserMode 58136
#define IDS_IDispatchAmbientsInvokeSupportsMnemonics 58137
#define IDS_IDispatchAmbientsInvokeDisplayAsDefault 58138
#define IDS_IOleContainerParseDisplayName 58139
#define IDS_IDispatchEventsGetTypeInfoCount 58140
#define IDS_IDispatchEventsGetTypeInfo  58141
#define IDS_IDispatchEventsGetIDsOfNames 58142
#define IDS_IDispatchEventsInvoke       58143
#define IDS_ISimpleFrameSitePreMessageFilter 58148
#define IDS_ISimpleFrameSitePostMessageFilter 58149
#define IDS_IPropertyNotifySinkOnRequestEdit 58150
#define IDS_IDispatchExtendedGetTypeInfoCount 58151
#define IDS_IDispatchExtendedGetTypeInfo 58152
#define IDS_IDispatchExtendedGetIDsOfNames 58153
#define IDS_IDispatchExtendedInvoke     58154
#define IDS_IOleClientSiteQI            58155
#define IDS_IOleInPlaceSiteQI           58156
#define IDS_IOleControlSiteQI           58157
#define IDS_IOleContainerQI             58158
#define IDS_IDispatchAmbientsQI         58159
#define IDS_IAdviseSinkQI               58160
#define IDS_ISimpleFrameSiteQI          58161
#define IDS_IOleInPlaceFrameAddress     58162
#define IDS_IOleContainerAddress        58163
#define IDS_WINDOWHANDLE                58164
#define IDS_FRAMEADDRESS                58165
#define IDS_DOCADDRESS                  58166
#define IDS_RECT                        58167
#define IDS_MENUWIDTHS                  58168
#define IDS_IDISPATCHADDRESS            58169
#define IDS_HIMETRIC                    58170
#define IDS_CONTAINER                   58171
#define IDS_IENUMUNKNOWNADDRESS         58172
#define IDS_NUMBER                      58173
#define IDS_ITYPEINFOADDRESS            58174
#define IDS_IDISPATCHEVENTS             58175
#define IDS_IPROPERTYNOTIFYSINK         58176
#define IDS_EXTENDEDCONTROL             58177
#define IDS_NOVALID_SCODE               58179
#define IDS_SOK                         58180
#define IDS_SFALSE                      58181
#define IDS_SCODEUNKNOWN                58182
#define IDS_ENOTIMPL                    58183
#define IDS_ENOINTERFACE                58184
#define IDS_EUNEXPECTED                 58185
#define IDS_EINVALIDARG                 58186
#define IDS_DISPEUNKNOWNNAME            58187
#define IDS_DISPEMEMBERNOTFOUND         58188
#define IDS_UNABLETOCREATEFILE          58189
#define IDS_INPLACEENOTOOLSPACE         58190
#define IDS_EFAIL                       58191

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
