# KallistiOS ##version##
#
# arch/dreamcast/util/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/03/23 07:11:43 bardtx Exp $


OBJS = vmu_pkg.o screenshot.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


