#------------------------------------------------------------------------------
#MemTest.mak
#------------------------------------------------------------------------------

PROJECT =	MemTest

PROJECT_SRC	= \
		MemTest.c\
		sbinit.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
