// [!ProjectName].idl : IDL source for [!ProjectName].exe
//

// This file will be processed by the MIDL tool to
// produce the type library ([!ProjectName].tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid([!TypelibGUID]),
	version(1.0),
	helpstring("[!ProjectName] 1.0 Type Library")
]
library [!ProjectNameSafe]Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
