	[
		object,
		uuid([!InterfaceGUID]),
		dual,
		helpstring("[!InterfaceName] Interface"),
		pointer_default(unique)
	]
	interface [!InterfaceName] : IDispatch
	{
[!if=(Toolbar, "TRUE")]
[!if!=(MethodName, "")]
		[id(1)] HRESULT [!MethodName]();
[!else]
		[id(1)] HRESULT SampleMethod();
[!endif]
[!endif]
	};
