	[
		object,
		uuid([!InterfaceGUID]),
	[!if=(Dual, "TRUE")]	dual,[!endif]
		helpstring("[!InterfaceName] Interface"),
		pointer_default(unique)
	]
	interface [!InterfaceName] : [!if=(Dual, "TRUE")]IDispatch[!else]IUnknown[!endif]
	{
[!if=(OnStartPage, "TRUE")]
		//Standard Server Side Component Methods
		HRESULT OnStartPage([in] IUnknown* piUnk);
		HRESULT OnEndPage();	
[!endif]
	};
