// ForumPool.idl : IDL source for ForumPool.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ForumPool.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(65E02892-E749-11D0-8862-00C04FB6F3B4),
		dual,
		helpstring("IPool Interface"),
		pointer_default(unique)
	]
	interface IPool : IDispatch
	{
		[id(1), helpstring("method GetForumService")] HRESULT GetForumService([out, retval] IDispatch ** ppoAdmin);
	};
[
	uuid(65E02885-E749-11D0-8862-00C04FB6F3B4),
	version(1.0),
	helpstring("ForumPool 1.0 Type Library")
]
library FORUMPOOLLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(68448136-E676-11D0-8862-00C04FB6F3B4),
		helpstring("ForumPool")
	]
	coclass CPool
	{
		[default] interface IPool;
	};
};
