USE_SMS=1
USE_SQL=1
dll=1

Proj=ViewDll

cDefines = -I ..

RFLAGS = -I ..

libs = ctl3d32s.lib gdi32.lib

!include <BkOffice.Mak>

All: $(ObjDir)\$(Proj).Dll

$(ObjDir)\$(Proj).Dll: $(@R).Obj $(@R).Res
