# KallistiOS ##version##
#
# arch/dreamcast/hardware/Makefile
# Copyright (C)2003 Dan Potter
#
# $Id: Makefile,v 1.1 2003/06/19 04:21:00 bardtx Exp $

BUILD_TARGET=loadable/libkos

OBJS = fs_utils.o

include $(KOS_BASE)/Makefile.prefab



