#------------------------------------------------------------------------------
# PWBrowser.mak
#------------------------------------------------------------------------------

PROJECT	= PWBrowser

PROJECT_SRC	= \
		main.c\
		njloop.c\
		sbinit.c\

SYSTEM_LIBS	= \
		sg_dpldr\
		nt_utl\
		ninja\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
