#------------------------------------------------------------------------------
#adxmlt.mak
#------------------------------------------------------------------------------

PROJECT =	adxmlt

PROJECT_SRC	= \
		main.c\
		sbinit.c\
		usr.c\
		dispstr.c\
		texchar.c\
		bpacsetup.c\
		bpamsetup.c\

SYSTEM_LIBS	= \
		cri_adxs\
		sofdec\
		sg_mwk2a\
		audio64\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
