#------------------------------------------------------------------------------
# SlideShow.mak
#------------------------------------------------------------------------------

PROJECT	= SlideShow

PROJECT_SRC	= \
		bpacsetup.c\
		sbinit.c\
		slideshow.c\

SYSTEM_LIBS	= \
		cri_adxs\
		sg_mwk2a\
		audio64\

GFXLIB		= KAMUI2
OUTPUT		= ELF
#COMPILER        = SHC

OPTIMIZE        = 1

DEBUG           = TRUE
LIST            = FALSE

include $(KATANA_ROOT)\sample\dc.inc
