# KallistiOS ##version##
#
# examples/dreamcast/kgl/Makefile
# (c)2002 Dan Potter 
#   
# $Id: Makefile,v 1.3 2002/04/20 03:48:55 axlen Exp $

all:
	$(KOS_MAKE) -C basic
	$(KOS_MAKE) -C benchmarks
	$(KOS_MAKE) -C demos
	$(KOS_MAKE) -C nehe

clean:
	$(KOS_MAKE) -C basic clean
	$(KOS_MAKE) -C benchmarks clean
	$(KOS_MAKE) -C demos clean
	$(KOS_MAKE) -C nehe clean
		
dist:
	$(KOS_MAKE) -C basic dist
	$(KOS_MAKE) -C benchmarks dist
	$(KOS_MAKE) -C demos dist
	$(KOS_MAKE) -C nehe dist


