//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WndTabs.rc
//
#define IDS_WNDTABS_LONGNAME            1
#define IDS_WNDTABS_DESCRIPTION         2
#define IDS_LANG_NAME_ENGLISH           10
#define IDS_LANG_NAME_NATIVE            11
#define IDS_LANG_AUTHOR                 12
#define IDS_LANG_FONT                   13
#define IDP_OLE_INIT_FAILED             100
#define IDS_OPTIONSSHEET_CAPTION        102
#define IDD_SW_WELCOME                  103
#define IDS_VERSION                     103
#define IDD_SW_TOOLBARS                 104
#define IDS_WWWLINK                     104
#define IDS_MAILLINK                    105
#define IDS_WWHIZ_WWW                   106
#define IDS_VA_WWW                      107
#define IDS_VERCHK_SERVER               108
#define IDS_VERCHK_FILE                 109
#define IDS_VERCHK_BETAFILE             110
#define IDS_AIC_WWW                     111
#define IDS_SH_WWW                      112
#define ID_UNAVAILABLE                  114
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR_LARGE               129
#define IDR_POPUP                       130
#define IDR_TOOLBAR_MEDIUM              131
#define IDI_MAIN                        131
#define IDB_MENUBUTTON                  132
#define IDR_MAINMENU                    133
#define IDB_BIGBUTTON                   133
#define IDI_ABOUT                       143
#define IDD_OPTPAGE_ARRANGEMENT         145
#define IDD_OPTPAGE_TABS_ARRANGEMENT    145
#define IDD_OPTPAGE_MISC                146
#define IDD_TOOLBAR_SETUP               148
#define IDR_ICONS                       153
#define IDB_SHELLCONTEXT                155
#define IDB_NUMBERS                     158
#define IDB_SW_TOOLBARS                 161
#define IDB_SW_SHORTCUTS                162
#define IDB_SW_WELCOME                  163
#define IDD_HOTKEY_WARNING              164
#define IDD_OPTPAGE_TABDISPLAY          165
#define IDD_OPTPAGE_TABS_CONTENT        165
#define IDD_SELECTCHAR                  169
#define IDB_SPLASH                      170
#define IDB_MENUBUTTON16                176
#define IDD_BUGREPORTS                  180
#define IDD_INFO                        181
#define IDI_RENUMBER                    182
#define IDI_REORDER                     183
#define IDI_INFO                        184
#define IDI_BUG                         185
#define IDD_REGISTRATION                186
#define IDI_NET                         186
#define IDD_WWW                         187
#define IDI_REGISTER                    187
#define IDB_PASTE                       188
#define IDI_LG_NET                      189
#define IDI_LG_MAIL                     190
#define IDI_WIZARD                      191
#define IDI_SCROLL                      192
#define IDB_2CLIPBOARD                  196
#define IDB_WINMAN                      197
#define IDD_CREDITS                     198
#define IDB_FILEMAN                     198
#define IDB_DS                          199
#define IDS_MENU_TT                     256
#define IDS_UNSAVED_TT                  257
#define IDS_DSWIN_TT                    258
#define IDS_TOUR_TT                     259
#define IDS_OPTIONS_TREEWIDTH           300
#define IDB_REORDER                     401
#define IDR_TOOLBAR_DYN                 403
#define IDR_SHELL_CONTEXT               407
#define IDB_OVERLAYS                    410
#define IDB_RENUMBER                    412
#define IDB_WIZARD                      413
#define IDB_NET                         414
#define IDB_SCROLL                      415
#define IDR_MENU1                       415
#define IDB_REGISTER                    416
#define IDR_COMMANDS                    416
#define IDB_BUG                         417
#define IDB_INFO                        418
#define IDB_TB_EMPTY                    422
#define IDR_POPUP_WINMAN                423
#define IDI_REG_OPT                     427
#define IDI_REG_OPT2                    428
#define IDD_REGISTER                    429
#define IDB_QMARK                       430
#define IDB_USERBTNS                    432
#define IDB_WNDTABSEXT                  433
#define IDD_DONT_SHOW_AGAIN             434
#define IDB_GO                          435
#define IDB_GO_HOVER                    436
#define IDR_DIR_OPTIONS                 437
#define IDD_SHORTCUTS                   438
#define IDB_RELOAD                      439
#define IDB_OK                          440
#define IDB_CANCEL                      441
#define IDB_NO                          442
#define IDB_GENERATE                    443
#define IDR_POPUP_TOOLBAR               444
#define IDD_WELCOME                     445
#define IDB_START                       446
#define IDB_KEYBOARD                    447
#define IDB_TOOLBAR_PIC                 448
#define IDB_HISTORY                     449
#define IDB_KEY                         450
#define IDB_BANNER                      451
#define IDB_INFO2                       454
#define IDB_LIGHT                       455
#define IDB_BULB2                       456
#define IDR_CLOSEBTN                    457
#define IDB_TABACTIVATE                 457
#define IDB_CUSTOMIZE                   458
#define IDD_CMD_SEL                     458
#define IDB_CUSTOMIZE2                  459
#define IDB_CUSTOMIZE3                  460
#define IDB_SW_BACKDROP                 461
#define IDB_SW_BANNER                   462
#define IDI_LANG_SEL                    464
#define IDI_LANG_DL                     465
#define IDC_SNAPMDI                     1000
#define IDS_HEADERERROR                 1000
#define IDC_SNAPWINDOW                  1001
#define IDS_DLLVERERROR                 1001
#define IDS_OPTIONSWARNING              1002
#define IDC_TOP                         1003
#define IDS_SHIFT1TO9WARNING            1003
#define IDC_BOTTOM                      1004
#define IDS_VERTWTTABCTRL               1004
#define IDC_LEFT                        1005
#define IDS_WRONGREG                    1005
#define IDC_RIGHT                       1006
#define IDS_NEWVER                      1006
#define IDS_THANKYOU                    1007
#define IDC_TAB                         1008
#define IDS_NOTTEXT                     1008
#define IDS_WELCOME_UPDATE              1009
#define IDS_WELCOME_UPDATE2             1010
#define IDS_ERR_AIC_REQUIRED            1011
#define IDC_SHOWICONS                   1012
#define IDS_ERR_WRONG_AIC               1012
#define IDC_FILL1TO9                    1013
#define IDS_MENU_RESET_CONFIRM          1013
#define IDC_STRIPDIRS                   1014
#define IDS_CONN_NONE                   1014
#define IDC_ROWS                        1015
#define IDS_CONN_LAN                    1015
#define IDC_SPIN                        1016
#define IDS_CONN_RAS                    1016
#define IDC_PRESERVE_ORDER              1017
#define IDS_RESET_USAGE                 1017
#define IDC_SHOWNUMBERS                 1018
#define IDS_ADDON_FOR_WTX               1018
#define IDS_VER_LATEST                  1019
#define IDS_VER_MORE_RECENT             1020
#define IDS_VER_LATEST_BETA             1021
#define IDS_VER_NEWER_BETA              1022
#define IDS_VER_MORE_RECENT_BETA        1023
#define IDC_PRESERVE_NUMBERING          1024
#define IDS_GROUP_NEEDS_WTX             1024
#define IDS_WARNINGS_RESET              1025
#define IDC_VERSION                     1026
#define IDS_HK_NOT_SET                  1026
#define IDS_WARN_MULTI_USE_REG          1027
#define IDC_CONTROL                     1028
#define IDS_WARN_KEY_BINDINGS           1028
#define IDC_SHIFT                       1029
#define IDS_WARN_OTHER_FLIPPER          1029
#define IDS_STRING1030                  1030
#define IDS_ADS_DISABLE                 1030
#define IDC_BOLDTEXT                    1031
#define IDS_ADS_RESTART                 1031
#define IDC_NO_WU                       1032
#define IDS_ADS_RESTART_REG             1032
#define IDC_DISP_RC                     1033
#define IDS_UNSUBCLASS_ERR              1033
#define IDC_USE_WWHIZ                   1034
#define IDS_RESTART                     1034
#define IDC_HOTKEY_ALT                  1035
#define IDS_CONFIRM_STOP_TRIAL          1035
#define IDS_NO_MORE_WTX                 1036
#define IDC_HOTKEY_TEXT                 1037
#define IDS_WARN_GOTO_CUSTOMIZE         1037
#define IDS_VERCHECK_PROMPT             1038
#define IDC_HOTKEY_DIR                  1039
#define IDS_NO_WWHIZINT_GROUP_PRJ       1039
#define IDS_CANT_UNDOCK                 1040
#define IDS_VER_EXPIRED                 1041
#define IDS_CUSTOMIZE                   1042
#define IDS_ERR_DOUBLE_SUBCLASS         1043
#define IDS_DONT_SHOW_MSG_AGAIN         1044
#define IDC_1TO9                        1045
#define IDS_DONT_CHECK_CONDITION_AGAIN  1045
#define IDC_F1TOF9                      1046
#define IDS_RESTART_FOR_KEYBINDING      1046
#define IDS_REMOVE_CUSTOM_SETTINGS      1047
#define IDS_CANT_DOWNLOAD_VER           1048
#define IDS_USER_TRIAL_REG              1049
#define IDS_OPTION_TRIAL_REG            1050
#define IDC_ALT                         1051
#define IDS_CONTROL_KEY_NAME            1051
#define IDC_ALLEDITORS                  1052
#define IDS_SHIFT_KEY_NAME              1052
#define IDC_MAINEDITOR                  1053
#define IDS_WARN_WWHIZINT               1053
#define IDC_LIST                        1054
#define IDS_ERR_LANG_CANT_LOAD          1054
#define IDC_HOTKEY                      1055
#define IDS_ERR_LANG_WRONG_VER          1055
#define IDC_DISP_RID                    1056
#define IDS_CHECKING_VERSION            1056
#define IDC_DISP_RESTYPE                1057
#define IDS_VERSION_OK                  1057
#define IDC_DISP_RESLANG                1058
#define IDS_ADDONS_NONE                 1058
#define IDS_TAB_CONTEXT_MENU_NAME       1059
#define ID_EDITORS                      1060
#define IDS_LANG_RESET_MENUS            1060
#define IDS_LANG_RESTART                1061
#define IDS_WARN_BAD_WWHIZINT           1062
#define IDC_HOTKEY_OPTIONS              1063
#define IDC_HOTKEY_RENUMBER             1066
#define IDC_HOTKEY_REORDER              1067
#define IDC_HOTKEY_GROUP_NEXT           1068
#define IDC_HOTKEY_GROUP_PREV           1069
#define IDC_STRIPEXT                    1073
#define IDC_LIMITCHARS                  1075
#define IDC_CHARLIMIT                   1076
#define IDC_USELIMITCHAR                1077
#define IDC_IGNOREEXT                   1078
#define IDC_LIMITRESCHARS               1079
#define IDC_LIMITCHARACTER              1080
#define IDC_PREFIXCHAR                  1081
#define IDC_SUFFIXCHAR                  1082
#define IDC_CHARCODE                    1083
#define IDC_RUNPROG                     1084
#define IDC_ANIMATE                     1085
#define IDC_BUGREPORTS                  1086
#define IDC_LIMITWIN                    1087
#define IDC_INFO                        1088
#define IDC_LIST_COMMANDS               1088
#define IDC_EDIT_DESCRIPTION            1089
#define IDC_WINLIMIT                    1090
#define IDC_VA_VER                      1091
#define IDC_WINLIMIT_DEBUG              1091
#define IDC_SH_VER                      1092
#define IDC_WWHIZ_VER                   1093
#define IDC_AUTOREFRESH                 1094
#define IDC_INTERVAL                    1095
#define IDC_INTERVALTEXT                1096
#define ID_EVERY                        1097
#define IDC_WINLIMIT_TEXT               1098
#define IDC_WINLIMIT_TEXT_DEBUG         1099
#define IDC_INFO_TEXT                   1103
#define IDC_USEWTTABCTRL                1104
#define IDC_GROUPTABS                   1105
#define IDC_GROUPPATH                   1106
#define IDC_CHANGEREG                   1112
#define IDC_CHANGESEL                   1113
#define IDC_GROUPRES                    1114
#define IDC_SHOWATTRIBS                 1115
#define IDC_WWW                         1117
#define IDC_MAIL                        1118
#define IDC_TOUR                        1119
#define IDC_REASON                      1121
#define IDC_REGISTER                    1122
#define ID_ARRANGEMENT                  1123
#define IDC_NAME                        1124
#define IDC_REGISTERED                  1132
#define IDC_RESET                       1136
#define IDC_RESET_MENUS                 1136
#define ID_REGFIRST                     1137
#define IDC_WWHIZ                       1138
#define IDC_VA                          1139
#define IDC_CHECKVER                    1140
#define IDC_LINK                        1141
#define ID_AICTEXT                      1142
#define ID_AICBORDER                    1143
#define ID_TEXTFIRST                    1144
#define IDC_LEFTMOST                    1148
#define IDC_RIGHTMOST                   1149
#define IDC_SEP                         1150
#define IDC_SEP2                        1151
#define IDC_CREDITS                     1153
#define IDC_STATIC_ORIENTATION          1154
#define IDC_STATIC_ROWS                 1156
#define IDC_STATIC_SNAPTO               1157
#define IDC_STATIC_ACCESSCONTEXTMENU    1158
#define IDC_STATIC_ACCESSCONTEXTMENU2   1159
#define IDC_STATIC_ACCESSCONTEXTMENU3   1160
#define IDC_STATIC_LIMIT_CHAR           1161
#define IDC_STATIC_RESOURCES            1162
#define IDC_DISP_DELIM                  1164
#define IDC_GROUPOPS                    1165
#define IDC_TABCOLOR_SEP                1166
#define IDC_STATIC_DELIM                1167
#define IDC_STATIC_REG_CLR              1168
#define IDC_STATIC_SEL_CLR              1169
#define IDC_INFO4BUGREP                 1170
#define IDC_TABCOLOR_SEP3               1170
#define ID_DISCLAMER                    1171
#define IDC_OTHERSTYLES                 1172
#define IDC_REGINFO                     1174
#define IDC_GROUP_SEP                   1176
#define IDC_GROUP_SEP2                  1177
#define IDC_CASCADING_WM                1184
#define IDC_NONE_WM                     1185
#define IDC_REGULAR_WM                  1186
#define IDC_AVAILABLE                   1186
#define IDC_CASCADING_FM                1187
#define IDC_RTFCOPY                     1187
#define IDC_NONE_FM                     1188
#define IDC_REGULAR_FM                  1189
#define IDC_TABCOLOR_SEP2               1189
#define IDC_CASCADING_CLIP              1190
#define IDC_MODEM                       1190
#define IDC_TABCOLOR_SEP4               1190
#define IDC_NONE_CLIP                   1191
#define IDC_LAN                         1191
#define IDC_REGULAR_CLIP                1192
#define IDC_AUTODETECT                  1192
#define IDC_CASCADING_DS                1193
#define IDC_NONE_DS                     1194
#define IDC_REGULAR_DS                  1195
#define IDC_WT_HELP                     1196
#define IDC_CASCADINGADDONS             1198
#define IDC_TEST                        1200
#define IDC_TEST_CONNECTION             1200
#define IDC_INFO_INET_SEND              1201
#define IDC_INFO_INET_PORT              1202
#define IDC_STATIC_EXT_FAIL             1203
#define ID_REG_NAME                     1204
#define IDC_STATIC_REG                  1205
#define IDC_STATIC_THANKYOU             1206
#define IDC_STATIC_AVAILABILITY         1208
#define IDC_SERIF                       1209
#define IDC_SANS_SERIF                  1210
#define IDC_SPLASH                      1211
#define IDC_EXPLORE                     1212
#define IDC_OPEN                        1213
#define IDC_FIXED                       1214
#define IDC_AUTO                        1215
#define IDC_STATIC_ICON                 1216
#define IDC_DONT_SHOW_AGAIN             1217
#define IDC_TEXT                        1218
#define IDC_TRIMPREFIX                  1219
#define IDC_USEPREFIXCHAR               1220
#define IDC_PREFIXES                    1221
#define IDC_TRIMSUFFIX                  1222
#define IDC_GO                          1223
#define IDC_GO_TO_TRIMMING              1223
#define IDC_USESUFFIXCHAR               1224
#define IDC_CHECKVER_NOW                1225
#define IDC_SUFFIXES                    1226
#define IDC_CHECKBETA_NOW               1227
#define IDC_MDI_ORDER                   1228
#define IDC_ALPHABETICAL                1229
#define IDC_SAVE_TAB_NUM                1230
#define IDC_NORAGGEDRIGHT               1231
#define IDC_AUTOOPENALT                 1232
#define IDC_LIMITGROUPS                 1233
#define IDC_LIMITWIN_DEBUG              1234
#define IDC_AUTOCLOSE_DEBUG             1235
#define IDC_DIRS                        1236
#define IDC_DIRPICKER                   1237
#define IDC_DIROPTIONS                  1238
#define IDC_BEGINTRIAL                  1239
#define IDC_KEYBOARD_CUST               1240
#define IDC_SET_SHORTCUTS               1241
#define IDC_BUTTON2                     1244
#define IDC_STOPTRIAL                   1244
#define IDC_GENERATE_SHORTCUTS          1245
#define IDC_RESET_SHOWONCE              1246
#define IDC_BUTTON3                     1247
#define IDC_KEYBOARD_CUST_BCG           1247
#define IDC_TOOLBAR_CUST                1248
#define IDC_CLEAR_SHORTCUTS             1249
#define IDC_SHOW_SUGGESTED              1250
#define IDC_FONT_STATIC                 1251
#define IDC_STATIC_PRESERVE_ORDER       1252
#define IDC_STATIC_MDI_ORDER            1253
#define IDC_STATIC_AUTOCLOSE_DEBUG      1254
#define IDC_STATIC_OCF_CMD              1255
#define IDC_INFO_WTX                    1256
#define IDC_BUTTON1                     1257
#define IDC_ENTER_KEY                   1257
#define IDC_FAQ                         1258
#define IDC_KEYBOARD_CUST_TAB_ACTIVATION 1259
#define IDC_CUSTOMIZE_CONTEXT_MENU_GROUPS 1260
#define IDC_SET_ACCESSCONTEXTMENU       1261
#define IDC_CUSTOMIZE_CONTEXT_MENU      1262
#define IDC_HYPERLINK_LANGUAGES         1263
#define IDC_MENUARROWS                  1290
#define IDC_SUPRESS_NOCMD               1291
#define IDH_TBSETUP_LIST_COMMANDS       1292
#define IDH_TBSETUP_EDIT_DESCRIPTION    1293
#define IDH_TBSETUP_OK                  1294
#define IDC_LIGHT                       1295
#define IDC_TAB_CLOSE_BTN               1296
#define IDC_FORCE_MINITB                1297
#define IDC_GROUPPRJ                    1298
#define IDC_SORTMINITB                  1299
#define IDC_STATIC_CLOSEBTN             1300
#define IDC_BACKFORWARD_IGNORE          1301
#define IDC_BACKFORWARD_CTRLTAB         1302
#define IDC_BACKFORWARD_TABORDER        1303
#define IDC_BACKFORWARD_CYCLEGROUP      1304
#define IDC_STOP_BUTTON                 1306
#define IDC_EDIT1                       1308
#define IDC_MIDBTN                      1308
#define IDC_BUTTON4                     1309
#define IDC_ASSIGN_MIDBTN               1309
#define IDC_CUSTOMIZE_WT_TOOLBAR        1310
#define IDC_ACCESSCONTEXTMENU           1310
#define IDC_STATIC_MIDBTN               1311
#define IDC_STATIC_INET_KBD             1312
#define IDC_RADIO1                      1313
#define IDC_RADIO2                      1314
#define IDC_TITLE                       1316
#define IDC_COMBO_LANG                  1318
#define IDC_STATIC_LANG_AUTHOR          1319
#define IDS_RO_TOGGLE                   1500
#define IDS_RO_MAKE_RW                  1501
#define IDS_RO_MAKE_RO                  1502
#define IDS_XERR_DLLLOAD                2000
#define IDS_XERR_BADDLL                 2001
#define IDS_XERR_REGISTRATION           2002
#define IDS_XERR_SCHEMA                 2003
#define IDS_XERR_VERSION                2003
#define IDS_XERR_OVERUSE                2004
#define IDS_XERR_EXPIRED                2005
#define IDS_XERR_GENERAL                2006
#define IDS_GOTOREG                     2100
#define IDS_WWW_REG                     2101
#define IDS_SW_EXIT_CONFIRM             2102
#define IDS_SW_TTL_INET                 2103
#define IDS_SW_SUBTTL_INET              2104
#define IDS_SW_TTL_KBD                  2105
#define IDS_SW_SUBTTL_KBD               2106
#define IDD_OPTPAGE_ABOUT               3023
#define IDD_SW_SHORTCUTS                3024
#define IDD_SW_FINISH                   3025
#define IDD_OPTPAGE_WTTABCTRL           3026
#define IDD_OPTPAGE_TABS_WTTABCTRL      3026
#define IDD_OPTPAGE_MENUS               3027
#define IDD_OPTPAGE_CUST_MENUS          3027
#define IDD_OPTPAGE_REGISTRATION        3029
#define IDD_CUSTOMIZE_OPTIONS           3030
#define IDD_OPTPAGE_TRIMMING            3031
#define IDD_OPTPAGE_TABS_TRIMMING       3031
#define IDD_OPTPAGE_ORDERING            3032
#define IDD_OPTPAGE_TABS_ORDERING       3032
#define IDD_OPTPAGE_WINFILEMAN          3033
#define IDD_OPTPAGE_WTTABCTRL2          3034
#define IDD_OPTPAGE_TABS_WTTABCTRL2     3034
#define IDD_OPTPAGE_CUST_KBD            3035
#define IDD_OPTPAGE_CUST_MOUSE          3036
#define IDD_OPTPAGE_CUST                3037
#define IDD_OPTPAGE_TABS                3038
#define IDD_CTX_MENU_GROUPS             3039
#define IDD_SHORTCUTS_TABS              3040
#define IDD_SW_INET                     3041
#define IDD_SW_KBD                      3042
#define IDD_SW_DONE                     3043
#define IDD_OPTPAGE_LANG                3044
#define IDC_CLOSE                       10771
#define ID_BUTTON00001                  10774
#define IDC_SELECT                      10776
#define IDC_SELECT_PREFIX_CHAR          10777
#define IDC_SELECT_SUFFIX_CHAR          10778
#define IDC_CLOSEALL                    10835
#define IDC_SAVE                        10836
#define IDC_SAVEALL                     10838
#define IDC_PROPERTIES                  10893
#define ID_DUMMY_FILESYSTEM_UNAVAILABLE 10916
#define ID_OVERLAY_1                    10917
#define ID_OVERLAY_2                    10918
#define ID_OVERLAY_3                    10919
#define ID_OVERLAY_4                    10920
#define ID_OVERLAY_5                    10921
#define ID_OVERLAY_6                    10922
#define ID_OVERLAY_7                    10923
#define ID_OVERLAY_8                    10924
#define ID_OVERLAY_9                    10925
#define ID_BUTTON00002                  10950
#define ID_BUTTON00003                  10951
#define IDC_ROATTR                      10953
#define IDC_CLOSEALLEXCEPT              10955
#define ID_CLIPBOARD                    10956
#define IDC_COPYFILENAME                10957
#define IDC_COPYDOC                     10958
#define IDC_COPYPATH                    10960
#define IDC_MINIMIZE_ALL                10961
#define IDC_CLOSEGROUP                  10962
#define IDC_SAVEGROUP                   10963
#define IDC_CLOSEEXCEPTGROUP            10964
#define IDC_FILEMAN                     10968
#define IDC_WINMAN                      10969
#define IDC_2CLIPBOARD                  10970
#define IDC_DS                          10971
#define IDC_SHELLCONTEXT                10972
#define ID_VIEW_CUSTOMIZE               10974
#define IDC_CUSTOMIZE                   10975
#define ID_SHELLCONTEXT                 10978
#define ID_BUTTON10979                  10979
#define ID_BUTTON10980                  10980
#define IDC_MENU                        10981
#define ID_ADDONS                       10983
#define IDC_OPENFOLDER                  10985
#define IDC_DS_INCLUDE_PATH             10987
#define IDC_DS_EXEC_PATH                10988
#define IDC_DS_SOURCE_PATH              10989
#define IDC_DS_LIB_PATH                 10990
#define IDC_WORKSPACE_DIR               10991
#define IDC_ACTIVE_PROJ_DIR             10992
#define IDC_ALL_PRJS_DIR                10993
#define IDC_GROUP_NEXT                  10994
#define IDC_GROUP_PREV                  10995
#define IDC_SMARTHELP                   11015
#define IDC_COPYFILENAME_NOPATH         11016
#define IDC_TAB_NEXT                    11017
#define IDC_TAB_PREV                    11018
#define IDC_ABOUT                       12000
#define IDC_OPTIONS                     12001
#define IDC_HEADERFLIP                  12002
#define IDC_RENUMBER                    12003
#define IDC_REORDER                     12004
#define IDC_OPENASTEXT                  12005
#define IDC_SETCURRDIR                  12006
#define IDC_GOTOTAB1                    12007
#define IDC_GOTOTAB2                    12008
#define IDC_GOTOTAB3                    12009
#define IDC_GOTOTAB4                    12010
#define IDC_GOTOTAB5                    12011
#define IDC_GOTOTAB6                    12012
#define IDC_GOTOTAB7                    12013
#define IDC_GOTOTAB8                    12014
#define IDC_GOTOTAB9                    12015
#define IDS_HELP                        12016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        465
#define _APS_NEXT_COMMAND_VALUE         11019
#define _APS_NEXT_CONTROL_VALUE         1321
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
