#------------------------------------------------------------------------------
#k2debug.mak
#------------------------------------------------------------------------------

PROJECT =	k2debug

PROJECT_SRC	= \
		BACKGRND.C\
		DISPSTR.C\
		KMSTOOL.C\
		KMSTRIPS.C\
		MAIN.C\
		sbinit.c\
		STRIP.C\
		STRIP1.C\
		TEXCHAR.C\

SYSTEM_LIBS	  = \
		  kamui2_d\


OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
