#------------------------------------------------------------------------------
#k2strips.mak
#------------------------------------------------------------------------------

PROJECT =	k2strips

PROJECT_SRC	= \
		BACKGRND.C\
		DISPSTR.C\
		KMSTOOL.C\
		KMSTRIPS.C\
		MAIN.C\
		sbinit.c\
		STRIP.C\
		STRIP1.C\
		TEXCHAR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
