// Machine generated IDispatch driver class(es) created with MFCDSPWZ tool.
/////////////////////////////////////////////////////////////////////////////
// Chart wrapper class

class Chart : public COleDispatchDriver
{
// Attributes
public:
	VARIANT GetArea3DGroup();
	void SetArea3DGroup(const VARIANT&);
	VARIANT GetAutoScaling();
	void SetAutoScaling(const VARIANT&);
	VARIANT GetBar3DGroup();
	void SetBar3DGroup(const VARIANT&);
	VARIANT GetChartArea();
	void SetChartArea(const VARIANT&);
	VARIANT GetChartTitle();
	void SetChartTitle(const VARIANT&);
	VARIANT GetColumn3DGroup();
	void SetColumn3DGroup(const VARIANT&);
	VARIANT GetCorners();
	void SetCorners(const VARIANT&);
	VARIANT GetCreator();
	void SetCreator(const VARIANT&);
	VARIANT GetDepthPercent();
	void SetDepthPercent(const VARIANT&);
	VARIANT GetDisplayBlanksAs();
	void SetDisplayBlanksAs(const VARIANT&);
	VARIANT GetElevation();
	void SetElevation(const VARIANT&);
	VARIANT GetFloor();
	void SetFloor(const VARIANT&);
	VARIANT GetGapDepth();
	void SetGapDepth(const VARIANT&);
	VARIANT GetHasAxis();
	void SetHasAxis(const VARIANT&);
	VARIANT GetHasLegend();
	void SetHasLegend(const VARIANT&);
	VARIANT GetHasTitle();
	void SetHasTitle(const VARIANT&);
	VARIANT GetHeightPercent();
	void SetHeightPercent(const VARIANT&);
	VARIANT GetIndex();
	void SetIndex(const VARIANT&);
	VARIANT GetLegend();
	void SetLegend(const VARIANT&);
	VARIANT GetLine3DGroup();
	void SetLine3DGroup(const VARIANT&);
	VARIANT GetName();
	void SetName(const VARIANT&);
	VARIANT GetNext();
	void SetNext(const VARIANT&);
	VARIANT GetOnDoubleClick();
	void SetOnDoubleClick(const VARIANT&);
	VARIANT GetOnSheetActivate();
	void SetOnSheetActivate(const VARIANT&);
	VARIANT GetOnSheetDeactivate();
	void SetOnSheetDeactivate(const VARIANT&);
	VARIANT GetPageSetup();
	void SetPageSetup(const VARIANT&);
	VARIANT GetParent();
	void SetParent(const VARIANT&);
	VARIANT GetPerspective();
	void SetPerspective(const VARIANT&);
	VARIANT GetPie3DGroup();
	void SetPie3DGroup(const VARIANT&);
	VARIANT GetPlotArea();
	void SetPlotArea(const VARIANT&);
	VARIANT GetPlotVisibleOnly();
	void SetPlotVisibleOnly(const VARIANT&);
	VARIANT GetPrevious();
	void SetPrevious(const VARIANT&);
	VARIANT GetProtectContents();
	void SetProtectContents(const VARIANT&);
	VARIANT GetProtectDrawingObjects();
	void SetProtectDrawingObjects(const VARIANT&);
	VARIANT GetRightAngleAxes();
	void SetRightAngleAxes(const VARIANT&);
	VARIANT GetRotation();
	void SetRotation(const VARIANT&);
	VARIANT GetSizeWithWindow();
	void SetSizeWithWindow(const VARIANT&);
	VARIANT GetSubType();
	void SetSubType(const VARIANT&);
	VARIANT GetSurfaceGroup();
	void SetSurfaceGroup(const VARIANT&);
	VARIANT GetType();
	void SetType(const VARIANT&);
	VARIANT GetVisible();
	void SetVisible(const VARIANT&);
	VARIANT GetWalls();
	void SetWalls(const VARIANT&);
	VARIANT GetWallsAndGridlines2D();
	void SetWallsAndGridlines2D(const VARIANT&);

// Operations
public:
	VARIANT Activate();
	VARIANT Application();
	VARIANT ApplyDataLabels(const VARIANT& Type, const VARIANT& LegendKey);
	VARIANT Arcs(const VARIANT& Index);
	VARIANT AreaGroups(const VARIANT& Index);
	VARIANT AutoFormat(const VARIANT& Gallery, const VARIANT& Format);
	VARIANT Axes(const VARIANT& Type, const VARIANT& AxisGroup);
	VARIANT BarGroups(const VARIANT& Index);
	VARIANT Buttons(const VARIANT& Index);
	VARIANT ChartGroups(const VARIANT& Index);
	VARIANT ChartObjects(const VARIANT& Index);
	VARIANT ChartWizard(const VARIANT& Source, const VARIANT& Gallery, const VARIANT& Format, const VARIANT& PlotBy, const VARIANT& CategoryLabels, const VARIANT& SeriesLabels, const VARIANT& HasLegend, const VARIANT& Title, 
		const VARIANT& CategoryTitle, const VARIANT& ValueTitle, const VARIANT& ExtraTitle);
	VARIANT CheckBoxes(const VARIANT& Index);
	VARIANT CheckSpelling(const VARIANT& CustomDictionary, const VARIANT& IgnoreUppercase, const VARIANT& AlwaysSuggest);
	VARIANT ColumnGroups(const VARIANT& Index);
	VARIANT Copy(const VARIANT& Before, const VARIANT& After);
	VARIANT CopyPicture(const VARIANT& Appearance, const VARIANT& Format, const VARIANT& Size);
	VARIANT CreatePublisher(const VARIANT& Edition, const VARIANT& Appearance, const VARIANT& Size, const VARIANT& ContainsPICT, const VARIANT& ContainsBIFF, const VARIANT& ContainsRTF, const VARIANT& ContainsVALU);
	VARIANT Delete();
	VARIANT Deselect();
	VARIANT DoughnutGroups(const VARIANT& Index);
	VARIANT DrawingObjects(const VARIANT& Index);
	VARIANT Drawings(const VARIANT& Index);
	VARIANT DropDowns(const VARIANT& Index);
	VARIANT _Evaluate(const VARIANT& Name);
	VARIANT Evaluate(const VARIANT& Name);
	VARIANT GroupBoxes(const VARIANT& Index);
	VARIANT GroupObjects(const VARIANT& Index);
	VARIANT Labels(const VARIANT& Index);
	VARIANT LineGroups(const VARIANT& Index);
	VARIANT Lines(const VARIANT& Index);
	VARIANT ListBoxes(const VARIANT& Index);
	VARIANT Move(const VARIANT& Before, const VARIANT& After);
	VARIANT OLEObjects(const VARIANT& Index);
	VARIANT OptionButtons(const VARIANT& Index);
	VARIANT Ovals(const VARIANT& Index);
	VARIANT Paste(const VARIANT& Type);
	VARIANT Pictures(const VARIANT& Index);
	VARIANT PieGroups(const VARIANT& Index);
	VARIANT PrintOut(const VARIANT& From, const VARIANT& To, const VARIANT& Copies, const VARIANT& Preview);
	VARIANT PrintPreview();
	VARIANT Protect(const VARIANT& Password, const VARIANT& DrawingObjects, const VARIANT& Contents, const VARIANT& Scenarios);
	VARIANT RadarGroups(const VARIANT& Index);
	VARIANT Rectangles(const VARIANT& Index);
	VARIANT SaveAs(const VARIANT& Filename, const VARIANT& FileFormat, const VARIANT& Password, const VARIANT& WriteResPassword, const VARIANT& ReadOnlyRecommended, const VARIANT& CreateBackup);
	VARIANT ScrollBars(const VARIANT& Index);
	VARIANT Select(const VARIANT& Replace);
	VARIANT SeriesCollection(const VARIANT& Index);
	VARIANT Spinners(const VARIANT& Index);
	VARIANT TextBoxes(const VARIANT& Index);
	VARIANT Unprotect(const VARIANT& Password);
	VARIANT XYGroups(const VARIANT& Index);
};
