# host compiler and flags
HOSTCC		= gcc
HOSTCFLAGS	= -O2
# cygwin may need this
#HOSTCFLAGS	= -O2 -D_WIN32

# you may have to change the paths for BFDLIB and BFDINCLUDE to
# the ones in your system

# these must point to your sh-elf bfd, not the system one
BFDLIB		= -L/usr/local/dcdev/lib -lbfd -liberty
BFDINCLUDE	= /usr/local/dcdev/include

# cygwin
# these must point to your sh-elf bfd, not the system one
#BFDLIB		= -L/usr/local/lib -lbfd -liberty -lintl
#BFDINCLUDE	= /usr/local/include

# sh-elf-stuff
TARGETCC	= sh-elf-gcc
TARGETCFLAGS	= -O2 -ml -m4
TARGETOBJCOPY	= sh-elf-objcopy
TARGETLD	= sh-elf-ld

# you generally shouldn't change this unless you are making forked
# versions (or test versions)
VERFLAGS	= -DDCLOAD_VERSION=\"1.0.4\"
TARGETCFLAGS	+= $(VERFLAGS)
HOSTCFLAGS	+= $(VERFLAGS)

# the ip of your dreamcast - set to 0.0.0.0 if you want to use arp on pc
DREAMCAST_IP	= 000.000.000.000
#DREAMCAST_IP	= 192.168.0.4
#DREAMCAST_IP	= 10.0.0.32

# dir to install dc-tool in
TOOLINSTALLDIR	= /usr/local/dcdev/bin
#TOOLINSTALLDIR = /usr/local/dc/bin

# uncomment this for cygwin
#EXECUTABLEEXTENSION = .exe
