all: dbg rtl

clean dbg rtl:
    cd d3dcheapbump
    nmake $(@B)
    cd ..\D3DDragonFly
    nmake $(@B)
    cd ..\D3DFortune
    nmake $(@B)
    cd ..\D3DKnot
    nmake $(@B)
    cd ..\D3DLightBeam
    nmake $(@B)
    cd ..\D3DMarble
    nmake $(@B)
    cd ..\D3DMaterials
    nmake $(@B)
    cd ..\D3DMipMapping
    nmake $(@B)
    cd ..\D3DScanner
    nmake $(@B)
    cd ..\D3DSiberian
    nmake $(@B)
    cd ..\D3DTextureFormats
    nmake $(@B)
    cd ..\D3DTrilinear
    nmake $(@B)
    cd ..\D3DVase
    nmake $(@B)
    cd ..\D3DWheel
    nmake $(@B)
    cd ..
