#------------------------------------------------------------------------------
#Hello.mak
#------------------------------------------------------------------------------

PROJECT =	Hello

PROJECT_SRC	= \
		HELLO.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
