// --------------------------------------------------------------------------------------------------------
//	mid_bank.h
//
// This header file was auto-generated by the Sega mkbank utility.
// Do not modify this file by hand.
//
// Rev:	2/3/2000 3:39 pm - File Generated
// --------------------------------------------------------------------------------------------------------

#ifndef	_MID_BANK_H
#define	_MID_BANK_H


#define		MID_BANK_FILENAME		"mid_bank.kat"
#define		MID_BANK_BANK_DATA_SIZE		13288
#define		MID_BANK_BANK_HEADER_SIZE		312
#define		MID_BANK_B3LOOP3_MID			0
#define		MID_BANK_B3ENVR28_MID			1
#define		MID_BANK_B3LOOP_MID			2
#define		MID_BANK_B3LOOP2_MID			3
#define		MID_BANK_B3_MID			4
#define		MID_BANK_JMUSIC_MID			5
#define		MID_BANK_MINUET_MID			6


#endif	//	end of _MID_BANK_H
