# KallistiOS ##version##
#
# net/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/02/10 20:31:43 bardtx Exp $

OBJS =  net_core.o net_arp.o net_input.o net_icmp.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



