# KallistiOS 1.2.0
#
# os/process/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.1.1.1 2001/09/26 07:05:01 bardtx Exp $

OBJS = elf.o process.o services.o svcmpx.o
SUBDIRS = 
BUILD_TARGET = addons/libos

include $(KOS_BASE)/Makefile.prefab

