#define IDD_PSAPIWorkingSetDemo     1

#define IDC_BUTTON_ABOUT    103
#define IDC_LB_WORKING_SET_DETAILS  102
#define IDC_LB_PROCESS_LIST 101
#define IDC_SHARED_MEMORY   104
#define IDC_PRIVATE_MEMORY  105
#define IDC_TOTAL_MEMORY    106
#define IDC_PAGE_TABLES     107
#define IDC_BUTTON_EMPTY_WORKING_SET    108
#define IDC_BUTTON_REFRESH_PROCESS_LIST 109
#define IDC_BUTTON_START_DELTA  110
#define IDC_BUTTON_END_DELTA    111
