# KallistiOS ##version##
#
# arch/dreamcast/math/Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/06/19 04:20:59 bardtx Exp $

# Dreamcast-specific math functions

BUILD_TARGET=loadable/libkos

OBJS = fmath.o matrix.o matrix3d.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


