##-----------------------------------------------------------------------------
##
##	FILE:		amabuse.mak
##
##	DESC:		Makefile for amabuse sample
##
##	HISTORY:	2000.01.xx	Reworked samples/boilerplates for R10 release.
##
##-----------------------------------------------------------------------------

PROJECT			= amabuse

PROJECT_SRC		=\
				main.c\
				sbinit.c\
				bpamsfx.c\
				bpprintf.c\
				bpacsetup.c\
				bpamsetup.c\
				bpamstream.c

SYSTEM_LIBS		=\
				audio64

OPTIMIZE		= 1

#COMPILER		= SHC
GFXLIB			= NINJA
OUTPUT			= ELF

DEBUG			= TRUE
LIST			= FALSE

include $(KATANA_ROOT)\sample\dc.inc
