#------------------------------------------------------------------------------
#k2flight.mak
#------------------------------------------------------------------------------

PROJECT =	k2flight

PROJECT_SRC	= \
		BAT.C\
		DISPSTR.C\
		FIRE.C\
		GROUND.C\
		KMFLIGHT.C\
		KMTOOLS.C\
		MAIN.C\
		sbinit.c\
		SHADOW.C\
		TEXCHAR.C\
		THORM.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
