#------------------------------------------------------------------------------
#k2gasfl.mak
#------------------------------------------------------------------------------

PROJECT =	k2gasfl

PROJECT_SRC	= \
		DISPSTR.C\
		GSFACE.C\
		GSFIRE.C\
		GSFIRER.C\
		GSGLASS.C\
		GSTORSO.C\
		KMGASFL.C\
		MAIN.C\
		sbinit.c\
		TEXCHAR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
