#------------------------------------------------------------------------------
#gdda2.mak
#------------------------------------------------------------------------------

PROJECT =	gdda2

PROJECT_SRC	= \
		njloop.c\
		sbinit.c\
		sndutls.c\
		test.c\

SYSTEM_LIBS     = \
                sg_sd\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
