# Makefile to build the Simple MAPI Client

!IFDEF MAPISAMP
HOME   = $(MAPISAMP)\simple.cli^\
COMMON = $(MAPISAMP)\common^\
!ELSE
HOME   = 
COMMON = ..\common^\
!ENDIF

!include <$(COMMON)win16.mak>

!IFNDEF NODEBUG
cflags = $(cflags) -DDEBUG
!ENDIF

PROJ = smpcli

# Main target dependencies

all: $(PROJ).exe

# Extra libraries needed, not defined in win16.mak

extralibs = mapi.lib

# Object files we need to build

OBJS = client.obj bitmap.obj 
COMMON_OBJS = pvalloc.obj
!IFNDEF NODEBUG
COMMON_OBJS = $(COMMON_OBJS) mapidbg.obj
!ENDIF

# Build the object files

{$(HOME)}.c.obj:
  set cl=-I$(COMMON) $(cdebug) $(cflags) $(cvars)
  $(cc) $**

pvalloc.obj: $(COMMON)pvalloc.c
  set cl=-I$(COMMON) $(cdebug) $(cflags) $(cvars)
  $(cc) $(COMMON)pvalloc.c

mapidbg.obj: $(COMMON)mapidbg.c
  set cl=-I$(COMMON) $(cdebug) $(cflags) $(cvars)
  $(cc) $(COMMON)mapidbg.c

# Build the resources

$(PROJ).res: $(HOME)client.rc $(HOME)client.ico $(HOME)client2.ico $(HOME)envelope.bmp
  set INCLUDE=$(INCLUDE);$(HOME);$(COMMON)
  $(rc) $(rcflags) $(rcvars) /fo $(PROJ).res $(HOME)client.RC

# Link it together to make the executable image

$(PROJ).exe: $(OBJS) $(COMMON_OBJS) $(PROJ).res
  echo $(OBJS) $(COMMON_OBJS) > link.txt
  echo $(PROJ).exe >> link.txt
  echo $(PROJ).map >> link.txt
  echo $(extralibs) $(guilibs) >> link.txt
  echo $(HOME)smpcli16.def >> link.txt
  $(link) $(ldebug) $(lflags) @link.txt
  $(rc) -t $(PROJ).res $@
!IFDEF MAPISAMP
  -copy $@ $(MAPISAMP)\bin\$(PLATFORM)
!ENDIF

# Clean up the intermediate files

clean:
  -del *.obj
  -del *.res
  -del *.exe
  -del *.map
  -del link.txt

