# KallistiOS ##version##
#
# loadable/modules/net Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/07/31 00:55:41 bardtx Exp $

DIRS = net_lwip

include ../../Makefile.subdirs

