#define IDM_ABOUT	     100

#define IDM_CALLWNDPROC      200
#define IDM_CBT 			 201
#define IDM_GETMESSAGE	     202
#define IDM_JOURNALPLAYBACK  203
#define IDM_JOURNALRECORD    204
#define IDM_KEYBOARD	     205
#define IDM_MOUSE			 206
#define IDM_MSGFILTER	     207
#define IDM_SYSMSGFILTER     208
#define IDM_DEBUG			 209

#define CALLWNDPROCINDEX     0
#define CBTINDEX			 (IDM_CBT			  - IDM_CALLWNDPROC)
#define GETMESSAGEINDEX      (IDM_GETMESSAGE	  - IDM_CALLWNDPROC)
#define JOURNALPLAYBACKINDEX (IDM_JOURNALPLAYBACK - IDM_CALLWNDPROC)
#define JOURNALRECORDINDEX   (IDM_JOURNALRECORD   - IDM_CALLWNDPROC)
#define KEYBOARDINDEX		 (IDM_KEYBOARD		  - IDM_CALLWNDPROC)
#define MOUSEINDEX			 (IDM_MOUSE			  - IDM_CALLWNDPROC)
#define MSGFILTERINDEX		 (IDM_MSGFILTER		  - IDM_CALLWNDPROC)
#define SYSMSGFILTERINDEX    (IDM_SYSMSGFILTER	  - IDM_CALLWNDPROC)
#define DEBUGFILTERINDEX	 (IDM_DEBUG			  - IDM_CALLWNDPROC)

#define NUMOFHOOKS 10


//
// Entry functions for the DLL
//
int FAR PASCAL InitHooksDll(HWND hwndMainWindow, int nWinLineHeight);
int FAR PASCAL PaintHooksDll(HDC hDC );
int FAR PASCAL InstallFilter (int nHookIndex, int nCode );
