# KallistiOS ##version##
#
# arch/ia32 Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/08/01 03:18:36 bardtx Exp $
	
SUBDIRS=kernel boot

include $(KOS_BASE)/Makefile.rules

all: subdirs
clean: clean_subdirs
