# KallistiOS ##version##
#
# arch Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/06/19 04:20:59 bardtx Exp $

all:
	$(MAKE) -C $(KOS_ARCH)

clean:
	$(MAKE) -C $(KOS_ARCH) clean
	
