TARGETNAME=testrun
TARGETTYPE=EXE

TARGETLIBS=       \
    coredll.lib   \
    fulllibc.lib  \
    dialogbx.lib  \
    ddraw.lib     \
    dinput.lib   \
    dplayx.lib    \
    dxguid.lib    \
    uuid.lib	    \
    mras.lib 	    \
    platutil.lib


OBJS=                          \
    $(TARGETPATH)\main.obj     \
    $(TARGETPATH)\usher.obj    \
    $(TARGETPATH)\rungame.res

!include "..\..\darksamp.mk"
