#------------------------------------------------------------------------------
#k2space.mak
#------------------------------------------------------------------------------

PROJECT =	k2space

PROJECT_SRC	= \
		DISPSTR.C\
		KMSPACE.C\
		KMTOOLS.C\
		MAIN.C\
		sbinit.c\
		SPACE.C\
		TEXCHAR.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
