#------------------------------------------------------------------------------
#k2cyberk.mak
#------------------------------------------------------------------------------

PROJECT =	k2cyberk

PROJECT_SRC	= \
		DISPSTR.C\
		KMCYBERK.C\
		MAIN.C\
		sbinit.c\
		TEXCHAR.C\
		TEXCYBERK.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
