# Makefile to build the MAPI Sample Transport Provider

!IFDEF MAPISAMP
HOME   = $(MAPISAMP)\peer.xp^\
COMMON = $(MAPISAMP)\common^\
!ELSE
HOME   = 
COMMON = ..\common^\
!ENDIF

!include <$(COMMON)win16.mak>

!IFNDEF NODEBUG
cflags = $(cflags) -DDEBUG
!ENDIF

PROJ     = SMPXP

# Main target dependencies

all: $(PROJ).dll

# Extra libraries needed, not defined in win32.mak

extralibs = mapi.lib

# Object files we need to build

OBJS1 =  XPBASE.OBJ XPDIALOG.OBJ XPGUID.OBJ XPLOGGER.OBJ XPOPTION.OBJ
OBJS2 =  XPQUEUE.OBJ XPRCVMSG.OBJ XPSNDMSG.OBJ XPSOF.OBJ XPSTATUS.OBJ
COMMON_OBJS = wep.obj
!IFNDEF NODEBUG
COMMON_OBJS = $(COMMON_OBJS) mapidbg.obj
!ENDIF

# Build the object files

{$(HOME)}.c.obj:
  $(cc) /I$(COMMON) $(cdebug) $(cflags) $(cvarsdll) $**

mapidbg.obj: $(COMMON)mapidbg.c
  $(cc) /I$(COMMON) $(cdebug) $(cflags) $(cvarsdll) $**

wep.obj: $(COMMON)wep.c
  $(cc) /I$(COMMON) $(cdebug) $(cflags) $(cvarsdll) $**

# Build the resources

$(PROJ).res: $(HOME)XPRESRC.RC $(HOME)XPRESRC.DLG
  set INCLUDE=$(INCLUDE);$(HOME);$(COMMON)
  $(rc) $(rcflags) $(rcvars) /fo $(PROJ).res $(HOME)XPRESRC.RC

# Link it together to make the executable image

$(PROJ).dll: $(OBJS1) $(OBJS2) $(COMMON_OBJS) $(PROJ).res
  echo $(OBJS1: = +) + > link.txt
  echo $(OBJS2: = +) + >> link.txt
  echo $(COMMON_OBJS: = +) >> link.txt
  echo $(PROJ).dll >> link.txt
  echo $(PROJ).map >> link.txt
  echo $(extralibs) $(guilibsdll) >> link.txt
  echo $(HOME)dll16.def >> link.txt
  $(link) $(ldebug) $(dlllflags) @link.txt
  $(rc) -t $(PROJ).res $@
!IFDEF MAPISAMP
  -copy $@ $(MAPISAMP)\bin\$(PLATFORM)
!ENDIF

# Clean up the intermediate files

clean:
  -del *.obj 
  -del *.res 
  -del *.lib 
  -del *.dll 
  -del *.map 
  -del link.txt

