#------------------------------------------------------------------------------
#k2njdraw.mak
#------------------------------------------------------------------------------

PROJECT =	k2njdraw

PROJECT_SRC	= \
		DISPSTR.C\
		F40.C\
		GTE.C\
		MAIN.C\
		sbinit.c\
		TEAPOT.C\
		TEXCHAR.C\
		TEXTURE.C\
		GTEASM.SRC\

SYSTEM_LIBS	= \
		kmutil\
		

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
