# KallistiOS ##version##
#
# examples/dreamcast/modem/Makefile
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile,v 1.1 2003/05/23 02:05:41 bardtx Exp $

all:
	$(KOS_MAKE) -C basic

clean:
	$(KOS_MAKE) -C basic clean
		
dist:
	$(KOS_MAKE) -C basic dist

