# KallistiOS ##version##
#
# arch/dreamcast/hardware/network/Makefile
# (c)2000-2001 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/01/30 02:30:20 bardtx Exp $

# Various network devices
OBJS = broadband_adapter.o lan_adapter.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab



