# KallistiOS ##version##
#
# arch/ps2/fs/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/11/06 08:36:40 bardtx Exp $

OBJS = fs_ps2load.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab

