#------------------------------------------------------------------------------
# scifterm.mak
#------------------------------------------------------------------------------

PROJECT	= scifterm

PROJECT_SRC	= \
		njloop.c\
		test.c\
		sbinit.c\

SYSTEM_LIBS	= \
		dmcast\
		ninja\
		mdmAPI\
		modem\

#SYSTEM_INCLUDE = $(DEF_INCLUDE)\pw

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
