//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VContain.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_VCONTATYPE                  129
#define IDD_RESULTS                     131
#define IDD_SPECIFIC_INTERFACES         132
#define IDD_PRE_VERIFY                  134
#define IDD_INSERT                      204
#define IDE_CANT_CREATE_CONTROL         1000
#define IDS_E_CANT_CREATE_CONTROL       1000
#define IDS_STRING1001                  1001
#define IDS_CONTROL_CREATED             1001
#define IDC_LIST_RESULT_TEXT            1002
#define IDS_CHECK_MAN_OR_OPT            1002
#define IDC_MAN_SUCCESS                 1003
#define IDS_CHECK_SUCC_OR_FAIL_OR_NV    1003
#define IDC_OLEOBJECT                   1004
#define IDS_FAILED                      1004
#define IDC_OLEINPLACEOJBECT            1005
#define IDC_MAN_FAILURES                1005
#define IDS_NOT_VERIFIED_W_HRESULT      1005
#define IDS_FAILED_W_HRESULT            1005
#define IDC_OLEINPLACEACTIVEOBJECT      1006
#define IDC_OPT_SUCCESS                 1006
#define IDS_PROVIDED_AND_IMPL           1006
#define IDC_OLECONTROL                  1007
#define IDC_OPT_FAILURES                1007
#define IDS_NOT_VERIFIED                1007
#define IDC_DATAOBJECT                  1008
#define IDC_NOT_VERIFIED                1008
#define IDC_MAN_NOT_VERIFIED            1008
#define IDS_OPT_SUCCESS_E_NOTIMPL       1008
#define IDS_PASSED                      1008
#define IDC_VIEWOBJECT2                 1009
#define IDC_OPT_NOT_VERIFIED            1009
#define IDS_E_CANT_DELETE_CONTROL       1009
#define IDC_EXTCONN                     1010
#define IDS_CONTROL_PASSED              1010
#define IDC_DISPATCH                    1011
#define IDS_CONTROL_FAILED              1011
#define IDC_CONNINTERFACES              1012
#define IDS_CHECK_OPT_FAIL              1012
#define IDC_PROVIDECLASSINFO            1013
#define IDC_SPECPROPPAGES               1014
#define IDC_PERSISTSTREAM               1015
#define IDS_NOT_VERIFIED_NO_HR          1015
#define IDC_PERSISTSTREAMINIT           1016
#define IDC_PERSISTSTORAGE              1017
#define IDC_PERSISTPROPBAG              1018
#define IDC_FILTER                      1018
#define IDC_OLECACHE                    1019
#define IDC_OLECACHE2                   1020
#define IDC_OLECACHECONTROL             1021
#define IDC_RUNOBJECT                   1022
#define IDC_CHK_MANDATORY               1026
#define IDC_CHK_OPTIONAL                1027
#define IDC_CHK_SUCCESS                 1028
#define IDC_CHK_FAIL                    1029
#define IDC_PROP_SET_YES                1030
#define IDC_UI_YES                      1031
#define IDC_AMBIENT_YES                 1032
#define IDC_LICENSING_YES               1033
#define IDC_MNEMONICS_YES               1034
#define IDC_PROPSMETHODS_YES            1035
#define IDC_NOTIFICATIONS_YES           1036
#define IDC_ACCELERATORS_YES            1037
#define IDC_PROPSMETHODS_LBL            1041
#define IDC_NOTIFICATIONS_LBL           1042
#define IDC_LICENSING_LBL               1044
#define IDC_UI_LBL                      1045
#define IDC_LINKS_YES                   1046
#define IDC_LINKS_LBL                   1047
#define IDC_PROP_PAGES_YES              1048
#define IDC_CHK_NOT_VERIFIED            1052
#define IDC_SAVE_TO_FILE                1053
#define IDC_PRE_VERIFY                  1054
#define IDC_INTRO_PRE_VERIFY            1054
#define IDC_INTRO_RESULTS               1055
#define IDC_PROP_PAGES_LBL              1056
#define IDS_OLEINPLACEOBJECT            2000
#define IDS_OLEINPLACEOBJECT_GW         2001
#define IDS_OLEINPLACEOBJECT_CSH        2002
#define IDS_OLEINPLACEOBJECT_IPD        2003
#define IDS_OLEINPLACEOBJECT_UID        2004
#define IDS_OLEINPLACEOBJECT_RAU        2005
#define IDS_OLEINPLACEOBJECT_SOR        2006
#define IDS_OLEINPLACEOBJECT_QI         2007
#define IDS_OLEOBJECT                   2020
#define IDS_OLEOBJECT_GCS               2021
#define IDS_OLEOBJECT_C                 2022
#define IDS_OLEOBJECT_DV_SHOW           2023
#define IDS_OLEOBJECT_A                 2024
#define IDS_OLEOBJECT_U                 2025
#define IDS_OLEOBJECT_SHS               2026
#define IDS_OLEOBJECT_SCS               2027
#define IDS_OLEOBJECT_GM                2028
#define IDS_OLEOBJECT_DV_PROPS          2029
#define IDS_OLEOBJECT_SM                2030
#define IDS_OLEOBJECT_IFD               2031
#define IDS_OLEOBJECT_GCD               2032
#define IDS_OLEOBJECT_EV                2033
#define IDS_OLEOBJECT_UP                2034
#define IDS_OLEOBJECT_IUTD              2035
#define IDS_OLEOBJECT_GUCID             2036
#define IDS_OLEOBJECT_GE                2037
#define IDS_OLEOBJECT_SE                2038
#define IDS_OLEOBJECT_GMS               2039
#define IDS_OLEOBJECT_SCSC              2040
#define IDS_OLEOBJECT_EA                2041
#define IDS_OLEOBJECT_GUT               2042
#define IDS_OLEOBJECT_SHN               2043
#define IDS_OLEOBJECT_DV_PRIMARY        2044
#define IDS_OLEOBJECT_DV_INSIDEOUT      2045
#define IDS_OLEOBJECT_DV_UIACTIVE       2046
#define IDS_OLEOBJECT_DV_HIDE           2047
#define IDS_OLEOBJECT_QI                2048
#define IDS_DATAOBJECT                  2060
#define IDS_DATAOBJECT_DA               2061
#define IDS_DATAOBJECT_DU               2062
#define IDS_DATAOBJECT_EDA              2063
#define IDS_DATAOBJECT_QGD              2064
#define IDS_DATAOBJECT_GD               2065
#define IDS_DATAOBJECT_GDH              2066
#define IDS_DATAOBJECT_GCFE             2067
#define IDS_DATAOBJECT_SD               2068
#define IDS_DATAOBJECT_EFE              2069
#define IDS_DATAOBJECT_QI               2070
#define IDS_DATAOBJECT12                2071
#define IDS_DATAOBJECT13                2072
#define IDS_VIEWOBJECT2                 2081
#define IDS_VIEWOBJECT2_F               2082
#define IDS_VIEWOBJECT2_U               2083
#define IDS_VIEWOBJECT2_SA              2084
#define IDS_VIEWOBJECT2_GA              2085
#define IDS_VIEWOBJECT2_GCS             2086
#define IDS_VIEWOBJECT2_GE              2087
#define IDS_VIEWOBJECT2_D               2088
#define IDS_VIEWOBJECT2_QI              2089
#define IDC_OLEINSERT_CLASSLIST         2103
#define IDS_DISPATCH                    3000
#define IDS_DISPATCH_GTIC               3001
#define IDS_DISPATCH_GTI                3002
#define IDS_DISPATCH_GIDON              3003
#define IDS_DISPATCH_I                  3004
#define IDS_E_DISPATCH_CANT_VERIFY      3005
#define IDS_DISPATCH_QI                 3006
#define IDS_PROVIDECLASSINFO            3021
#define IDS_PROVIDECLASSINFO_GCI        3022
#define IDS_PROVIDECLASSINFO_QI         3023
#define IDS_PERSISTSTORAGE              3040
#define IDS_PERSISTSTORAGE_ID           3041
#define IDS_PERSISTSTORAGE_L            3042
#define IDS_PERSISTSTORAGE_S            3043
#define IDS_PERSISTSTORAGE_SC           3044
#define IDS_PERSISTSTORAGE_HOS          3045
#define IDS_PERSISTSTORAGE_IN           3046
#define IDS_PERSISTSTORAGE_QI           3047
#define IDS_OLEINPLACEACTIVEOBJECT      3060
#define IDS_OLEINPLACEACTIVEOBJECT_GW   3061
#define IDS_OLEINPLACEACTIVEOBJECT_TA   3062
#define IDS_OLEINPLACEACTIVEOBJECT_EM   3063
#define IDS_OLEINPLACEACTIVEOBJECT_ODWA 3064
#define IDS_OLEINPLACEACTIVEOBJECT_OFWA 3065
#define IDS_OLEINPLACEACTIVEOBJECT_CSH  3066
#define IDS_OLEINPLACEACTIVEOBJECT_RB   3067
#define IDS_SETACTIVEOBJECT             3068
#define IDS_OLECONTROL                  3080
#define IDS_OLECONTROL_GCI              3081
#define IDS_OLECONTROL_OM               3082
#define IDS_OLECONTROL_OAPC             3083
#define IDS_OLECONTROL_FE               3084
#define IDS_OLECONTROL_QI               3085
#define IDS_EXTERNAL_CONNECTION         4000
#define IDS_EXTERNAL_CONNECTION_AC      4001
#define IDS_EXTERNAL_CONNECTION_RC      4002
#define IDS_EXTERNAL_CONNECTION_QI      4003
#define IDS_CONNECTIONPOINTCONTAINER    4020
#define IDS_CONNECTIONPOINTCONTAINER_ECP 4021
#define IDS_CONNECTIONPOINTCONTAINER_FCP 4022
#define IDS_CONNECTIONPOINT             4023
#define ICS_CONNECTIONPOINT             4023
#define IDS_PROPERTYNOTIFYSINK_OUT      4024
#define IDS_CONNECTIONPOINTCONTAINER_QI 4024
#define IDS_CONNECTIONPOINT_EC          4025
#define IDS_CONNECTIONPOINT_GCI         4026
#define IDS_CONNECTIONPOINT_A           4027
#define IDS_CONNECTIONPOINT_U           4028
#define IDS_CONNECTIONPOINT_GCPC        4029
#define IDS_SPECIFYPROPERTYPAGES        4040
#define IDS_SPECIFYPROPERTYPAGES_GP     4041
#define IDS_SPECIFYPROPERTYPAGES_QI     4042
#define IDS_PERSISTSTREAM               4060
#define IDS_PERSISTSTREAM_GSM           4061
#define IDS_PERSISTSTREAM_S             4062
#define IDS_PERSISTSTREAM_L             4063
#define IDS_PERSISTSTREAM_ID            4064
#define IDS_PERSISTSTREAM_QI            4065
#define IDS_PERSISTSTREAMINIT           4080
#define IDS_PERSISTSTREAMINIT_IN        4081
#define IDS_PERSISTSTREAMINIT_ID        4082
#define IDS_PERSISTSTREAMINIT_GSM       4083
#define IDS_PERSISTSTREAMINIT_S         4084
#define IDS_PERSISTSTREAMINIT_L         4085
#define IDS_PERSISTSTREAMINIT_QI        4086
#define IDS_PERSISTPROPERTYBAG          5000
#define IDS_PERSISTPROPERTYBAG_GCID     5001
#define IDS_PERSISTPROPERTYBAG_IN       5002
#define IDS_PERSISTPROPERTYBAG_L        5003
#define IDS_PERSISTPROPERTYBAG_S        5004
#define IDS_PERSISTPROPERTYBAG_QI       5005
#define IDS_OLECACHE                    5020
#define IDS_OLECACHE_IC                 5021
#define IDS_OLECACHE_C                  5022
#define IDS_OLECACHE_EC                 5023
#define IDS_OLECACHE_SD                 5024
#define IDS_OLECACHE_U                  5025
#define IDS_OLECACHE_QI                 5026
#define IDS_OLECACHE2                   5040
#define IDS_OLECACHE2_UC                5041
#define IDS_OLECACHE2_DC                5042
#define IDS_OLECACHE2_QI                5043
#define IDS_OLECACHECONTROL             5060
#define IDS_OLECACHECONTROL_OR          5061
#define IDS_OLECACHECONTROL_OS          5062
#define IDS_OLECACHECONTROL_QI          5063
#define IDS_RUNNABLEOBJECT              5080
#define IDS_RUNNABLEOBJECT_GRC          5081
#define IDS_RUNNABLEOBJECT_IR           5082
#define IDS_RUNNABLEOBJECT_LR           5083
#define IDS_RUNNABLEOBJECT_R            5084
#define IDS_RUNNABLEOBJECT_SCO          5085
#define IDS_RUNNABLEOBJECT_QI           5086
#define IDS_CLASSFACTORY                6000
#define IDS_CLASSFACTORY2               6001
#define IDS_OPTIONAL                    6002
#define IDS_MANDATORY                   6003
#define IDS_E_CANT_CREATE_ISTREAM       6004
#define IDS_E_CANT_CREATE_ISTORAGE      6005
#define IDS_CLOSE_PROP_PAGES            6006
#define IDS_E_NO_PRE_VERIFY_INFO        6007
#define IDS_E_CANT_SAVE                 6008
#define IDS_ATTRIB_BINDABLE             6009
#define IDS_NV_PREV_FAILURE             6020
#define IDS_E_UNEXPECTED                6021
#define IDS_E_OUTOFMEMORY               6022
#define IDS_E_INVALIDARG                6023
#define IDS_E_NOINTERFACE               6024
#define IDS_E_POINTER                   6025
#define IDS_E_HANDLE                    6026
#define IDS_E_ABORT                     6027
#define IDS_E_ACCESSDENIED              6028
#define IDS_E_NOTIMPL                   6029
#define IDS_UNSPECIFIED                 6030
#define IDS_NV_NOT_APPLICABLE           6031
#define IDS_NV_UNKNOWN_REASON           6032
#define IDS_NV_AUTO_EXCEPTION           6033
#define IDS_FORMAT_AUTO_EXCEPTION       6034
#define IDS_E_FAIL_UNSPECIFIED          6035
#define IDS_NV_PREV_NOT_IMPL            6036
#define IDS_S_OK                        6037
#define IDS_S_FALSE                     6038
#define IDS_DV_E_FORMATETC              6039
#define IDS_DV_E_DVTARGETDEVICE         6040
#define IDS_DV_E_STGMEDIUM              6041
#define IDS_DV_E_STATDATA               6042
#define IDS_DV_E_LINDEX                 6043
#define IDS_DV_E_TYMED                  6044
#define IDS_DV_E_CLIPFORMAT             6045
#define IDS_DV_E_DVASPECT               6046
#define IDS_DISP_E_UNKNOWNINTERFACE     6047
#define IDS_DISP_E_MEMBERNOTFOUND       6048
#define IDS_DISP_E_PARAMNOTFOUND        6049
#define IDS_DISP_E_TYPEMISMATCH         6050
#define IDS_DISP_E_UNKNOWNNAME          6051
#define IDS_DISP_E_NONAMEDARGS          6052
#define IDS_DISP_E_BADVARTYPE           6053
#define IDS_DISP_E_EXCEPTION            6054
#define IDS_DISP_E_OVERFLOW             6055
#define IDS_DISP_E_BADINDEX             6056
#define IDS_DISP_E_UNKNOWNLCID          6057
#define IDS_DISP_E_ARRAYISLOCKED        6058
#define IDS_DISP_E_BADPARAMCOUNT        6059
#define IDS_DISP_E_PARAMNOTOPTIONAL     6060
#define IDS_DISP_E_BADCALLEE            6061
#define IDS_DISP_E_NOTACOLLECTION       6062
#define IDS_DATA_S_SAMEFORMATEC         6063
#define IDS_NOT_QI_OBTAINED             6064
#define ID_INSERT_CONTROL               32771
#define ID_VERIFY_CONTROL               32773
#define ID_VERIFY_CONTROL_MANDATORY     32774
#define ID_VERIFY_CONTROL_OPTIONAL      32775
#define ID_VERIFY_SPECIFIC              32777
#define ID_VIEW_RESULTS                 32778
#define ID_DELETECONTROL                32779
#define ID_FILE_DELETE                  32783
#define ID_FILE_INSERT                  32786
#define ID_TOOLBAR                      32787
#define ID_STATUS_BAR                   32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
