
;==============================================================================
;  Microsoft (R) Bloodhound (tm). Copyright (C) 1991-1992.
;
;  MODULE: bherr.inc
;
;  This source file contains Bloodhound error code definitions.
;==============================================================================


BHERR_SUCCESS                        =  0
BHERR_INTERNAL_ERROR                 =  1
BHERR_INVALID_HFILTER                =  2
BHERR_CAPTURING                      =  3
BHERR_NOT_CAPTURING                  =  4
BHERR_NO_MORE_FRAMES                 =  5
BHERR_BUFFER_TOO_SMALL               =  6

BHERR_DRIVER_NOT_FOUND               =  9
BHERR_ADDRESS_ALREADY_EXISTS         =  10
BHERR_INVALID_HFRAME                 =  11
BHERR_INVALID_HPARSER                =  12
BHERR_INVALID_HPROPERTY              =  13
BHERR_LOCKED                         =  14
BHERR_STACK_EMPTY                    =  15
BHERR_STACK_OVERFLOW                 =  16
BHERR_TOO_MANY_PARSERS               =  17
BHERR_FILE_NOT_FOUND                 =  18
BHERR_OUT_OF_MEMORY                  =  19
BHERR_CAPTURE_PAUSED                 =  20
BHERR_NO_BUFFERS                     =  21
BHERR_BUFFERS_ALREADY_EXIST          =  22
BHERR_NOT_LOCKED                     =  23
BHERR_OUT_OF_RANGE                   =  24
BHERR_LOCK_NESTING_TOO_DEEP          =  25
BHERR_LOAD_PARSER_FAILED             =  26
BHERR_UNLOAD_PARSER_FAILED           =  27
BHERR_INVALID_HADDRESSDB             =  28
BHERR_ADDRESS_NOT_FOUND              =  29
BHERR_NETWORK_NOT_PRESENT            =  30
BHERR_NO_PROPERTYDB                  =  31
BHERR_PROPERTY_NOT_FOUND             =  32
BHERR_INVALID_HPROPERTYDB            =  33
BHERR_PARSER_NOT_ENABLED             =  34
BHERR_PARSER_NOT_FOUND               =  35
BHERR_INVALID_PARSER_DLL             =  36
BHERR_NO_ATTACHED_PROPERTIES         =  37
BHERR_NO_FRAMES                      =  38
BHERR_INVALID_FILE_FORMAT            =  39
BHERR_COULD_NOT_CREATE_TEMPFILE      =  40
BHERR_OUT_OF_DOS_MEMORY              =  41
BHERR_NO_PARSERS_ENABLED             =  42
BHERR_NAME_NOT_FOUND                 =  43
BHERR_ADDR_NOT_FOUND                 =  44
BHERR_NAMETABLE_FULL                 =  45
BHERR_UNKNOWN_MACTYPE                =  46
BHERR_ROUTING_INFO_NOT_PRESENT       =  47
BHERR_INVALID_HNETWORK               =  48
BHERR_NETWORK_ALREADY_OPENED         =  49
BHERR_NETWORK_NOT_OPENED             =  50
BHERR_FRAME_NOT_FOUND                =  51
BHERR_BAD_FILE_FORMAT                =  52
BHERR_NO_HANDLES                     =  53
BHERR_INVALID_NETWORK_ID             =  54
BHERR_INVALID_HCAPTURE               =  55
BHERR_PARSER_ALREADY_ENABLED         =  56
