/*****************************************************************************\
*                                                                             *
* olectlid.h    Master definition of GUIDs for OLE Controls                   *
*                                                                             *
*               OLE Version 2.0                                               *
*                                                                             *
*               Copyright 1992 - 1998 Microsoft Corp. All rights reserved. *
*                                                                             *
\*****************************************************************************/

#pragma message("WARNING: your code should #include olectl.h instead")
#include <olectl.h>
