USE_SQL=1
USE_ODS=1
console=1

Proj = ProcSrv

cDefines=-DDBNTWIN32

!include <BkOffice.Mak>

All: $(ObjDir)\$(Proj).Exe $(ObjDir)\Service.Exe

$(ObjDir)\$(Proj).Exe: $(@R).Obj

$(ObjDir)\Service.Exe: $(@R).Obj

