USE_SMS=1
console=1

Proj=SrvInst

cDefines=-DSTRICT=1 -D_NTWIN -D_CONSOLE=1 -D_AFX_NOFORCE_LIBS

!include <BkOffice.Mak>

All: $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(@R).obj

$(ObjDir)\$(Proj).Obj: $(@B).Cpp

