# KallistiOS ##version##
#
# examples/dreamcast/pvr/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/09/28 04:18:55 bardtx Exp $

all:
	$(KOS_MAKE) -C plasma
	$(KOS_MAKE) -C pvrmark
	$(KOS_MAKE) -C pvrmark_strips
	$(KOS_MAKE) -C pvrmark_strips_direct
	$(KOS_MAKE) -C texture_render

clean:
	$(KOS_MAKE) -C plasma clean
	$(KOS_MAKE) -C pvrmark clean
	$(KOS_MAKE) -C pvrmark_strips clean
	$(KOS_MAKE) -C pvrmark_strips_direct clean
	$(KOS_MAKE) -C texture_render clean
		
dist:
	$(KOS_MAKE) -C plasma dist
	$(KOS_MAKE) -C pvrmark dist
	$(KOS_MAKE) -C pvrmark_strips dist
	$(KOS_MAKE) -C pvrmark_strips_direct dist
	$(KOS_MAKE) -C texture_render dist


