#------------------------------------------------------------------------------
#k2toyp.mak
#------------------------------------------------------------------------------

PROJECT =	k2toyp

PROJECT_SRC	= \
		BACKGRND.C\
		DISPSTR.C\
		KMPTOOL.C\
		KMTOYP.C\
		MAIN.C\
		sbinit.c\
		TEXCHAR.C\
		WOOD.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
