# KallistiOS ##version##
#
# arch/dreamcast Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.5 2003/06/19 04:29:00 bardtx Exp $
	
SUBDIRS=hardware kernel

include $(KOS_BASE)/Makefile.rules

all: subdirs
clean: clean_subdirs
