#------------------------------------------------------------------------------
#sg_gd4.mak
#------------------------------------------------------------------------------

PROJECT =	sg_gd4

PROJECT_SRC	= \
		fstr.c\
		msg.c\
		njloop.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
