#
# Libdream Examples
# (c)2000-2001 Dan Potter
#

TARGET = $(BIN).elf

all: $(TARGET)

include $(KOS_BASE)/Makefile.rules

clean:
	rm -f $(TARGET) $(OBJS) $(EXTRA_CLEAN)

rm-elf:
	rm -f $(TARGET)

$(TARGET): $(OBJS)
	$(KOS_CC) $(KOS_CFLAGS) $(KOS_LDFLAGS) -o $(TARGET) $(KOS_START) \
		$(OBJS) $(DATAOBJS) $(OBJEXTRA) \
		$(EXTRA_LIBS) $(KOS_LIBS)

run: $(TARGET)
	$(KOS_LOADER) $(TARGET)

dist:
	rm -f $(OBJS) $(EXTRA_CLEAN)
	$(KOS_STRIP) $(TARGET)

