#------------------------------------------------------------------------------
#k2trees.mak
#------------------------------------------------------------------------------

PROJECT =	k2trees

PROJECT_SRC	= \
		DISPSTR.C\
		KMTREES.C\
		kmtrtool.c\
		LEAF.C\
		MAIN.C\
		sbinit.c\
		SNOW.C\
		TEXCHAR.C\
		TREE.C\
		TTREE.C\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
