#------------------------------------------------------------------------------
#kbd3.mak
#------------------------------------------------------------------------------

PROJECT =	kbd3

PROJECT_SRC	= \
		DBGCONS.C\
		KC_JPNRM.C\
		KC_JPSFT.C\
		KC_UKNRM.C\
		KC_UKSFT.C\
		KC_USNRM.C\
		KC_USSFT.C\
		KEYBOARD.C\
		njloop.c\
		sbinit.c\
		test.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
