#------------------------------------------------------------------------------
#k2mask.mak
#------------------------------------------------------------------------------

PROJECT =	k2mask

PROJECT_SRC	= \
		BACKRFL1.C\
		BACKRFL2.C\
		BACKRFL3.C\
		DISPSTR.C\
		KMMASK.C\
		MAIN.C\
		MFRONT01.C\
		MFRONT02.C\
		MFRONT03.C\
		MGROUND.C\
		MREFLECT.C\
		sbinit.c\
		TEXCHAR.C\

SYSTEM_LIBS	  = \
		  kmutil\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
