#------------------------------------------------------------------------------
#lcd2.mak
#------------------------------------------------------------------------------

PROJECT =	lcd2

PROJECT_SRC	= \
		lcdlib.c\
		main.c\
		sbinit.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
