#------------------------------------------------------------------------------
#oneshot64.mak
#------------------------------------------------------------------------------

PROJECT =	oneshot64

PROJECT_SRC	= \
		sbinit.c\
		sndutls.c\
		njloop.c\
		sample.c\

SYSTEM_LIBS     = \
                sg_sd\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	NINJA
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
