# KallistiOS ##version##
#
# examples/ps2/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/10/27 23:41:13 bardtx Exp $

all:
	$(KOS_MAKE) -C basic

clean:
	$(KOS_MAKE) -C basic clean
		
dist:
	$(KOS_MAKE) -C basic dist

