#------------------------------------------------------------------------------
#QuikTst2.mak
#------------------------------------------------------------------------------

PROJECT =	QuikTst2

PROJECT_SRC	= \
		QuikTst2.c\
		sbinit.c\

OPTIMIZE =	1

#COMPILER =	SHC
GFXLIB =	KAMUI2
OUTPUT =	ELF

DEBUG  =	TRUE
LIST   =	FALSE

include $(KATANA_ROOT)\Sample\dc.inc
